# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\qtlab_cyclops\source\gui\cyclops\panels\designer\laserscan_simple.ui'
#
# Created: Fri Aug 05 11:53:51 2011
#      by: PyQt4 UI code generator 4.7.3
#/
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Panel(object):
    def setupUi(self, Panel):
        Panel.setObjectName("Panel")
        Panel.setEnabled(True)
        Panel.resize(800, 770)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Panel.sizePolicy().hasHeightForWidth())
        Panel.setSizePolicy(sizePolicy)
        Panel.setMinimumSize(QtCore.QSize(800, 770))
        #self.chart_frequency = TimeTracePlot(Panel)
        #self.chart_frequency.setGeometry(QtCore.QRect(10, 10, 781, 201))
        #self.chart_frequency.setMinimumSize(QtCore.QSize(0, 150))
        #self.chart_frequency.setFrameShape(QtGui.QFrame.StyledPanel)
        #self.chart_frequency.setFrameShadow(QtGui.QFrame.Raised)
        #self.chart_frequency.setObjectName("chart_frequency")
        self.CurrentFrequency = QtGui.QDoubleSpinBox(Panel)
        self.CurrentFrequency.setEnabled(False)
        self.CurrentFrequency.setGeometry(QtCore.QRect(181, 510, 91, 22))
        self.CurrentFrequency.setDecimals(3)
        self.CurrentFrequency.setMinimum(468000.0)
        self.CurrentFrequency.setMaximum(472000.0)
        self.CurrentFrequency.setSingleStep(0.001)
        self.CurrentFrequency.setProperty("value", 470000.0)
        self.CurrentFrequency.setObjectName("CurrentFrequency")
        self.label = QtGui.QLabel(Panel)
        self.label.setGeometry(QtCore.QRect(30, 514, 141, 16))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(Panel)
        self.label_2.setGeometry(QtCore.QRect(30, 550, 111, 16))
        self.label_2.setObjectName("label_2")
        self.FrequencyReference = QtGui.QDoubleSpinBox(Panel)
        self.FrequencyReference.setEnabled(False)
        self.FrequencyReference.setGeometry(QtCore.QRect(180, 547, 91, 22))
        self.FrequencyReference.setDecimals(3)
        self.FrequencyReference.setMinimum(468000.0)
        self.FrequencyReference.setMaximum(472000.0)
        self.FrequencyReference.setSingleStep(0.001)
        self.FrequencyReference.setProperty("value", 470400.0)
        self.FrequencyReference.setObjectName("FrequencyReference")
        self.label_3 = QtGui.QLabel(Panel)
        self.label_3.setGeometry(QtCore.QRect(30, 583, 141, 16))
        self.label_3.setObjectName("label_3")
        self.RelativeFrequency = QtGui.QDoubleSpinBox(Panel)
        self.RelativeFrequency.setEnabled(False)
        self.RelativeFrequency.setGeometry(QtCore.QRect(180, 580, 91, 22))
        self.RelativeFrequency.setDecimals(3)
        self.RelativeFrequency.setMinimum(-4000.0)
        self.RelativeFrequency.setMaximum(4000.0)
        self.RelativeFrequency.setSingleStep(0.001)
        self.RelativeFrequency.setProperty("value", 0.0)
        self.RelativeFrequency.setObjectName("RelativeFrequency")
        self.label_4 = QtGui.QLabel(Panel)
        self.label_4.setGeometry(QtCore.QRect(30, 613, 141, 16))
        self.label_4.setObjectName("label_4")
        self.FrequencySetpoint = QtGui.QDoubleSpinBox(Panel)
        self.FrequencySetpoint.setGeometry(QtCore.QRect(180, 610, 91, 22))
        self.FrequencySetpoint.setDecimals(3)
        self.FrequencySetpoint.setMinimum(-1000.0)
        self.FrequencySetpoint.setMaximum(1000.0)
        self.FrequencySetpoint.setSingleStep(0.001)
        self.FrequencySetpoint.setProperty("value", 0.0)
        self.FrequencySetpoint.setObjectName("FrequencySetpoint")
        self.StepUp = QtGui.QPushButton(Panel)
        self.StepUp.setEnabled(False)
        self.StepUp.setGeometry(QtCore.QRect(220, 675, 51, 23))
        self.StepUp.setObjectName("StepUp")
        self.StepDown = QtGui.QPushButton(Panel)
        self.StepDown.setEnabled(False)
        self.StepDown.setGeometry(QtCore.QRect(220, 705, 51, 23))
        self.StepDown.setObjectName("StepDown")
        self.label_5 = QtGui.QLabel(Panel)
        self.label_5.setGeometry(QtCore.QRect(30, 694, 81, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(Panel)
        self.label_6.setGeometry(QtCore.QRect(180, 695, 31, 16))
        self.label_6.setObjectName("label_6")
        self.FrequencyStep = QtGui.QSpinBox(Panel)
        self.FrequencyStep.setEnabled(False)
        self.FrequencyStep.setGeometry(QtCore.QRect(110, 690, 61, 22))
        self.FrequencyStep.setMinimum(1)
        self.FrequencyStep.setMaximum(1000)
        self.FrequencyStep.setProperty("value", 100)
        self.FrequencyStep.setObjectName("FrequencyStep")
        self.LockFrequency = QtGui.QCheckBox(Panel)
        self.LockFrequency.setEnabled(True)
        self.LockFrequency.setGeometry(QtCore.QRect(50, 654, 91, 17))
        self.LockFrequency.setCheckable(True)
        self.LockFrequency.setChecked(False)
        self.LockFrequency.setObjectName("LockFrequency")
        self.LaserOn = QtGui.QCheckBox(Panel)
        self.LaserOn.setEnabled(True)
        self.LaserOn.setGeometry(QtCore.QRect(40, 250, 70, 17))
        self.LaserOn.setCheckable(True)
        self.LaserOn.setChecked(False)
        self.LaserOn.setObjectName("LaserOn")
        self.label_7 = QtGui.QLabel(Panel)
        self.label_7.setGeometry(QtCore.QRect(430, 550, 81, 16))
        self.label_7.setObjectName("label_7")
        self.ScanCount = QtGui.QSpinBox(Panel)
        self.ScanCount.setGeometry(QtCore.QRect(550, 550, 81, 22))
        self.ScanCount.setMinimum(1)
        self.ScanCount.setMaximum(1000)
        self.ScanCount.setObjectName("ScanCount")
        self.DCStarkShiftSweep = QtGui.QCheckBox(Panel)
        self.DCStarkShiftSweep.setGeometry(QtCore.QRect(670, 520, 101, 17))
        self.DCStarkShiftSweep.setObjectName("DCStarkShiftSweep")
        self.label_8 = QtGui.QLabel(Panel)
        self.label_8.setGeometry(QtCore.QRect(650, 550, 41, 16))
        self.label_8.setObjectName("label_8")
        self.DCGate = QtGui.QSpinBox(Panel)
        self.DCGate.setGeometry(QtCore.QRect(710, 550, 81, 22))
        self.DCGate.setMinimum(1)
        self.DCGate.setMaximum(2)
        self.DCGate.setObjectName("DCGate")
        self.label_9 = QtGui.QLabel(Panel)
        self.label_9.setGeometry(QtCore.QRect(650, 580, 81, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtGui.QLabel(Panel)
        self.label_10.setGeometry(QtCore.QRect(650, 640, 81, 16))
        self.label_10.setObjectName("label_10")
        self.DCStart = QtGui.QDoubleSpinBox(Panel)
        self.DCStart.setGeometry(QtCore.QRect(710, 580, 81, 22))
        self.DCStart.setDecimals(3)
        self.DCStart.setMinimum(0.0)
        self.DCStart.setMaximum(2.0)
        self.DCStart.setSingleStep(0.001)
        self.DCStart.setObjectName("DCStart")
        self.DCstepsize = QtGui.QDoubleSpinBox(Panel)
        self.DCstepsize.setGeometry(QtCore.QRect(710, 640, 81, 22))
        self.DCstepsize.setDecimals(3)
        self.DCstepsize.setMinimum(-20.0)
        self.DCstepsize.setMaximum(20.0)
        self.DCstepsize.setSingleStep(0.1)
        self.DCstepsize.setObjectName("DCstepsize")
        self.LaserInitialize = QtGui.QCheckBox(Panel)
        self.LaserInitialize.setGeometry(QtCore.QRect(300, 440, 151, 17))
        self.LaserInitialize.setChecked(False)
        self.LaserInitialize.setObjectName("LaserInitialize")
        self.PulseAOM = QtGui.QCheckBox(Panel)
        self.PulseAOM.setGeometry(QtCore.QRect(590, 360, 81, 17))
        self.PulseAOM.setObjectName("PulseAOM")
        self.label_11 = QtGui.QLabel(Panel)
        self.label_11.setGeometry(QtCore.QRect(580, 390, 91, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtGui.QLabel(Panel)
        self.label_12.setGeometry(QtCore.QRect(580, 420, 91, 16))
        self.label_12.setObjectName("label_12")
        self.PowerLevelPulse = QtGui.QDoubleSpinBox(Panel)
        self.PowerLevelPulse.setGeometry(QtCore.QRect(710, 420, 81, 22))
        self.PowerLevelPulse.setDecimals(1)
        self.PowerLevelPulse.setMaximum(1000.0)
        self.PowerLevelPulse.setSingleStep(0.1)
        self.PowerLevelPulse.setProperty("value", 50.0)
        self.PowerLevelPulse.setObjectName("PowerLevelPulse")
        self.label_13 = QtGui.QLabel(Panel)
        self.label_13.setGeometry(QtCore.QRect(580, 450, 91, 16))
        self.label_13.setObjectName("label_13")
        self.PowerLevelScan = QtGui.QDoubleSpinBox(Panel)
        self.PowerLevelScan.setGeometry(QtCore.QRect(710, 450, 81, 22))
        self.PowerLevelScan.setDecimals(1)
        self.PowerLevelScan.setMaximum(1000.0)
        self.PowerLevelScan.setSingleStep(0.1)
        self.PowerLevelScan.setObjectName("PowerLevelScan")
        self.DCStop = QtGui.QDoubleSpinBox(Panel)
        self.DCStop.setGeometry(QtCore.QRect(710, 610, 81, 22))
        self.DCStop.setDecimals(3)
        self.DCStop.setMinimum(0.0)
        self.DCStop.setMaximum(2.0)
        self.DCStop.setSingleStep(0.001)
        self.DCStop.setObjectName("DCStop")
        self.label_14 = QtGui.QLabel(Panel)
        self.label_14.setGeometry(QtCore.QRect(650, 610, 81, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtGui.QLabel(Panel)
        self.label_15.setGeometry(QtCore.QRect(330, 410, 91, 16))
        self.label_15.setObjectName("label_15")
        self.InitialWait = QtGui.QDoubleSpinBox(Panel)
        self.InitialWait.setGeometry(QtCore.QRect(430, 410, 81, 22))
        self.InitialWait.setObjectName("InitialWait")
        self.label_16 = QtGui.QLabel(Panel)
        self.label_16.setGeometry(QtCore.QRect(330, 290, 81, 16))
        self.label_16.setObjectName("label_16")
        self.StartVoltage = QtGui.QDoubleSpinBox(Panel)
        self.StartVoltage.setGeometry(QtCore.QRect(430, 290, 81, 22))
        self.StartVoltage.setDecimals(4)
        self.StartVoltage.setMinimum(-3.0)
        self.StartVoltage.setMaximum(3.0)
        self.StartVoltage.setSingleStep(0.0003)
        self.StartVoltage.setObjectName("StartVoltage")
        self.label_17 = QtGui.QLabel(Panel)
        self.label_17.setGeometry(QtCore.QRect(330, 320, 81, 10))
        self.label_17.setObjectName("label_17")
        self.StepVoltage = QtGui.QDoubleSpinBox(Panel)
        self.StepVoltage.setGeometry(QtCore.QRect(430, 320, 81, 22))
        self.StepVoltage.setDecimals(4)
        self.StepVoltage.setMinimum(-3.0)
        self.StepVoltage.setMaximum(3.0)
        self.StepVoltage.setSingleStep(0.0003)
        self.StepVoltage.setProperty("value", -0.0009)
        self.StepVoltage.setObjectName("StepVoltage")
        self.label_18 = QtGui.QLabel(Panel)
        self.label_18.setGeometry(QtCore.QRect(330, 330, 91, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtGui.QLabel(Panel)
        self.label_19.setGeometry(QtCore.QRect(330, 380, 81, 16))
        self.label_19.setObjectName("label_19")
        self.IntegrationTime = QtGui.QSpinBox(Panel)
        self.IntegrationTime.setGeometry(QtCore.QRect(430, 380, 81, 22))
        self.IntegrationTime.setObjectName("IntegrationTime")
        self.label_20 = QtGui.QLabel(Panel)
        self.label_20.setGeometry(QtCore.QRect(580, 280, 101, 16))
        self.label_20.setObjectName("label_20")
        self.WavemeterChannel = QtGui.QSpinBox(Panel)
        self.WavemeterChannel.setGeometry(QtCore.QRect(710, 280, 81, 22))
        self.WavemeterChannel.setMinimum(1)
        self.WavemeterChannel.setMaximum(5)
        self.WavemeterChannel.setObjectName("WavemeterChannel")
        self.label_21 = QtGui.QLabel(Panel)
        self.label_21.setGeometry(QtCore.QRect(580, 310, 81, 16))
        self.label_21.setObjectName("label_21")
        self.CounterChannel = QtGui.QSpinBox(Panel)
        self.CounterChannel.setGeometry(QtCore.QRect(710, 310, 81, 22))
        self.CounterChannel.setMinimum(1)
        self.CounterChannel.setMaximum(5)
        self.CounterChannel.setProperty("value", 5)
        self.CounterChannel.setObjectName("CounterChannel")
        self.ScanBack = QtGui.QCheckBox(Panel)
        self.ScanBack.setGeometry(QtCore.QRect(460, 440, 151, 17))
        self.ScanBack.setObjectName("ScanBack")
        self.label_22 = QtGui.QLabel(Panel)
        self.label_22.setGeometry(QtCore.QRect(330, 470, 101, 16))
        self.label_22.setObjectName("label_22")
        self.ScanBackTime = QtGui.QDoubleSpinBox(Panel)
        self.ScanBackTime.setEnabled(False)
        self.ScanBackTime.setGeometry(QtCore.QRect(430, 470, 81, 22))
        self.ScanBackTime.setObjectName("ScanBackTime")
        self.label_23 = QtGui.QLabel(Panel)
        self.label_23.setGeometry(QtCore.QRect(430, 580, 111, 16))
        self.label_23.setObjectName("label_23")
        self.FrequencyAveraging = QtGui.QSpinBox(Panel)
        self.FrequencyAveraging.setGeometry(QtCore.QRect(550, 580, 81, 22))
        self.FrequencyAveraging.setMinimum(1)
        self.FrequencyAveraging.setMaximum(100)
        self.FrequencyAveraging.setProperty("value", 10)
        self.FrequencyAveraging.setObjectName("FrequencyAveraging")
        self.label_24 = QtGui.QLabel(Panel)
        self.label_24.setGeometry(QtCore.QRect(430, 610, 121, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtGui.QLabel(Panel)
        self.label_25.setGeometry(QtCore.QRect(430, 640, 111, 16))
        self.label_25.setObjectName("label_25")
        self.ModeHopThreshold = QtGui.QSpinBox(Panel)
        self.ModeHopThreshold.setGeometry(QtCore.QRect(550, 640, 81, 22))
        self.ModeHopThreshold.setMinimum(1)
        self.ModeHopThreshold.setMaximum(10000)
        self.ModeHopThreshold.setProperty("value", 1000)
        self.ModeHopThreshold.setObjectName("ModeHopThreshold")
        self.StartScan = QtGui.QPushButton(Panel)
        self.StartScan.setGeometry(QtCore.QRect(510, 220, 81, 23))
        self.StartScan.setFlat(False)
        self.StartScan.setObjectName("StartScan")
        self.AbortScan = QtGui.QPushButton(Panel)
        self.AbortScan.setEnabled(True)
        self.AbortScan.setGeometry(QtCore.QRect(710, 220, 81, 23))
        self.AbortScan.setFlat(False)
        self.AbortScan.setObjectName("AbortScan")
        self.label_32 = QtGui.QLabel(Panel)
        self.label_32.setGeometry(QtCore.QRect(10, 310, 81, 16))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtGui.QLabel(Panel)
        self.label_33.setGeometry(QtCore.QRect(10, 340, 81, 16))
        self.label_33.setObjectName("label_33")
        self.PiezoVoltage = QtGui.QDoubleSpinBox(Panel)
        self.PiezoVoltage.setEnabled(False)
        self.PiezoVoltage.setGeometry(QtCore.QRect(100, 310, 81, 22))
        self.PiezoVoltage.setProperty("value", 50.0)
        self.PiezoVoltage.setObjectName("PiezoVoltage")
        self.SetPiezoVoltage = QtGui.QPushButton(Panel)
        self.SetPiezoVoltage.setEnabled(False)
        self.SetPiezoVoltage.setGeometry(QtCore.QRect(200, 310, 81, 23))
        self.SetPiezoVoltage.setFlat(False)
        self.SetPiezoVoltage.setObjectName("SetPiezoVoltage")
        self.ScanVoltage = QtGui.QDoubleSpinBox(Panel)
        self.ScanVoltage.setEnabled(False)
        self.ScanVoltage.setGeometry(QtCore.QRect(100, 340, 81, 22))
        self.ScanVoltage.setDecimals(3)
        self.ScanVoltage.setMinimum(-3.0)
        self.ScanVoltage.setMaximum(3.0)
        self.ScanVoltage.setSingleStep(0.001)
        self.ScanVoltage.setObjectName("ScanVoltage")
        self.SetScanVoltage = QtGui.QPushButton(Panel)
        self.SetScanVoltage.setEnabled(False)
        self.SetScanVoltage.setGeometry(QtCore.QRect(200, 340, 81, 23))
        self.SetScanVoltage.setFlat(False)
        self.SetScanVoltage.setObjectName("SetScanVoltage")
        self.FrequencyInterpolationStep = QtGui.QSpinBox(Panel)
        self.FrequencyInterpolationStep.setGeometry(QtCore.QRect(550, 610, 81, 22))
        self.FrequencyInterpolationStep.setMinimum(1)
        self.FrequencyInterpolationStep.setMaximum(1000)
        self.FrequencyInterpolationStep.setProperty("value", 10)
        self.FrequencyInterpolationStep.setObjectName("FrequencyInterpolationStep")
        self.label_34 = QtGui.QLabel(Panel)
        self.label_34.setGeometry(QtCore.QRect(30, 740, 151, 16))
        self.label_34.setObjectName("label_34")
        self.LockFrequencyDeviation = QtGui.QDoubleSpinBox(Panel)
        self.LockFrequencyDeviation.setEnabled(False)
        self.LockFrequencyDeviation.setGeometry(QtCore.QRect(180, 740, 91, 22))
        self.LockFrequencyDeviation.setDecimals(3)
        self.LockFrequencyDeviation.setMinimum(-4000.0)
        self.LockFrequencyDeviation.setMaximum(4000.0)
        self.LockFrequencyDeviation.setSingleStep(0.001)
        self.LockFrequencyDeviation.setProperty("value", 0.0)
        self.LockFrequencyDeviation.setObjectName("LockFrequencyDeviation")
        self.label_35 = QtGui.QLabel(Panel)
        self.label_35.setGeometry(QtCore.QRect(10, 370, 81, 16))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtGui.QLabel(Panel)
        self.label_36.setGeometry(QtCore.QRect(10, 400, 81, 16))
        self.label_36.setObjectName("label_36")
        self.Gate1Voltage = QtGui.QDoubleSpinBox(Panel)
        self.Gate1Voltage.setGeometry(QtCore.QRect(100, 370, 81, 22))
        self.Gate1Voltage.setMinimum(0.0)
        self.Gate1Voltage.setMaximum(2.0)
        self.Gate1Voltage.setObjectName("Gate1Voltage")
        self.Gate2Voltage = QtGui.QDoubleSpinBox(Panel)
        self.Gate2Voltage.setGeometry(QtCore.QRect(100, 400, 81, 22))
        self.Gate2Voltage.setMinimum(0.0)
        self.Gate2Voltage.setMaximum(2.0)
        self.Gate2Voltage.setSingleStep(0.1)
        self.Gate2Voltage.setObjectName("Gate2Voltage")
        self.SetGate1Voltage = QtGui.QPushButton(Panel)
        self.SetGate1Voltage.setGeometry(QtCore.QRect(200, 370, 81, 23))
        self.SetGate1Voltage.setFlat(False)
        self.SetGate1Voltage.setObjectName("SetGate1Voltage")
        self.SetGate2Voltage = QtGui.QPushButton(Panel)
        self.SetGate2Voltage.setGeometry(QtCore.QRect(200, 400, 81, 23))
        self.SetGate2Voltage.setFlat(False)
        self.SetGate2Voltage.setObjectName("SetGate2Voltage")
        self.PulseDuration = QtGui.QSpinBox(Panel)
        self.PulseDuration.setGeometry(QtCore.QRect(710, 390, 81, 22))
        self.PulseDuration.setMinimum(1)
        self.PulseDuration.setMaximum(10000000)
        self.PulseDuration.setProperty("value", 10000)
        self.PulseDuration.setObjectName("PulseDuration")
        self.ScanSteps = QtGui.QSpinBox(Panel)
        self.ScanSteps.setGeometry(QtCore.QRect(430, 350, 81, 22))
        self.ScanSteps.setMinimum(100)
        self.ScanSteps.setMaximum(65535)
        self.ScanSteps.setObjectName("ScanSteps")
        self.Label_999 = QtGui.QLabel(Panel)
        self.Label_999.setGeometry(QtCore.QRect(330, 350, 81, 16))
        self.Label_999.setObjectName("Label_999")
        self.Comments = QtGui.QTextEdit(Panel)
        self.Comments.setGeometry(QtCore.QRect(290, 680, 501, 81))
        self.Comments.setObjectName("Comments")
        self.label_26 = QtGui.QLabel(Panel)
        self.label_26.setGeometry(QtCore.QRect(293, 663, 61, 16))
        self.label_26.setObjectName("label_26")
        self.PauseScan = QtGui.QPushButton(Panel)
        self.PauseScan.setEnabled(True)
        self.PauseScan.setGeometry(QtCore.QRect(610, 220, 81, 23))
        self.PauseScan.setFlat(False)
        self.PauseScan.setObjectName("PauseScan")
        self.GateSweep = QtGui.QCheckBox(Panel)
        self.GateSweep.setGeometry(QtCore.QRect(360, 220, 81, 17))
        self.GateSweep.setObjectName("GateSweep")
        self.ModulateGate = QtGui.QCheckBox(Panel)
        self.ModulateGate.setGeometry(QtCore.QRect(360, 240, 181, 17))
        self.ModulateGate.setObjectName("ModulateGate")
        self.label_38 = QtGui.QLabel(Panel)
        self.label_38.setGeometry(QtCore.QRect(10, 280, 81, 16))
        self.label_38.setObjectName("label_38")
        self.ScanRangeCenter = QtGui.QDoubleSpinBox(Panel)
        self.ScanRangeCenter.setGeometry(QtCore.QRect(100, 280, 81, 22))
        self.ScanRangeCenter.setMinimum(-300.0)
        self.ScanRangeCenter.setMaximum(300.0)
        self.ScanRangeCenter.setObjectName("ScanRangeCenter")
        self.SetScanRangeCenter = QtGui.QPushButton(Panel)
        self.SetScanRangeCenter.setGeometry(QtCore.QRect(200, 280, 81, 23))
        self.SetScanRangeCenter.setFlat(False)
        self.SetScanRangeCenter.setObjectName("SetScanRangeCenter")
        self.label_27 = QtGui.QLabel(Panel)
        self.label_27.setGeometry(QtCore.QRect(430, 520, 71, 16))
        self.label_27.setObjectName("label_27")
        self.CurrentScan = QtGui.QSpinBox(Panel)
        self.CurrentScan.setEnabled(False)
        self.CurrentScan.setGeometry(QtCore.QRect(550, 520, 81, 22))
        self.CurrentScan.setObjectName("CurrentScan")
        self.PulseAOM_manual = QtGui.QPushButton(Panel)
        self.PulseAOM_manual.setGeometry(QtCore.QRect(540, 250, 101, 23))
        self.PulseAOM_manual.setFlat(False)
        self.PulseAOM_manual.setObjectName("PulseAOM_manual")
        self.SkipToNext = QtGui.QPushButton(Panel)
        self.SkipToNext.setEnabled(True)
        self.SkipToNext.setGeometry(QtCore.QRect(660, 250, 89, 23))
        self.SkipToNext.setFlat(False)
        self.SkipToNext.setObjectName("SkipToNext")
        self.AutoOptimizeXY = QtGui.QCheckBox(Panel)
        self.AutoOptimizeXY.setGeometry(QtCore.QRect(300, 520, 101, 17))
        self.AutoOptimizeXY.setObjectName("AutoOptimizeXY")
        self.AutoOptimizeZ = QtGui.QCheckBox(Panel)
        self.AutoOptimizeZ.setGeometry(QtCore.QRect(300, 550, 101, 17))
        self.AutoOptimizeZ.setObjectName("AutoOptimizeZ")
        self.label_28 = QtGui.QLabel(Panel)
        self.label_28.setGeometry(QtCore.QRect(300, 580, 101, 16))
        self.label_28.setObjectName("label_28")
        self.OptimizeInterval = QtGui.QSpinBox(Panel)
        self.OptimizeInterval.setGeometry(QtCore.QRect(370, 580, 51, 22))
        self.OptimizeInterval.setMinimum(1)
        self.OptimizeInterval.setMaximum(999)
        self.OptimizeInterval.setObjectName("OptimizeInterval")
        self.MWOn = QtGui.QCheckBox(Panel)
        self.MWOn.setEnabled(True)
        self.MWOn.setGeometry(QtCore.QRect(170, 250, 70, 17))
        self.MWOn.setCheckable(True)
        self.MWOn.setChecked(False)
        self.MWOn.setObjectName("MWOn")
        self.label_29 = QtGui.QLabel(Panel)
        self.label_29.setGeometry(QtCore.QRect(580, 480, 111, 16))
        self.label_29.setObjectName("label_29")
        self.PowerLevelOn = QtGui.QDoubleSpinBox(Panel)
        self.PowerLevelOn.setGeometry(QtCore.QRect(710, 480, 81, 22))
        self.PowerLevelOn.setDecimals(1)
        self.PowerLevelOn.setMaximum(1000.0)
        self.PowerLevelOn.setSingleStep(0.1)
        self.PowerLevelOn.setProperty("value", 250.0)
        self.PowerLevelOn.setObjectName("PowerLevelOn")
        self.label_39 = QtGui.QLabel(Panel)
        self.label_39.setGeometry(QtCore.QRect(10, 430, 81, 16))
        self.label_39.setObjectName("label_39")
        self.MWfrequency = QtGui.QDoubleSpinBox(Panel)
        self.MWfrequency.setEnabled(False)
        self.MWfrequency.setGeometry(QtCore.QRect(100, 430, 81, 22))
        self.MWfrequency.setDecimals(6)
        self.MWfrequency.setMinimum(1e-06)
        self.MWfrequency.setMaximum(6.0)
        self.MWfrequency.setSingleStep(0.1)
        self.MWfrequency.setProperty("value", 2.88)
        self.MWfrequency.setObjectName("MWfrequency")
        self.SetMWfrequency = QtGui.QPushButton(Panel)
        self.SetMWfrequency.setEnabled(False)
        self.SetMWfrequency.setGeometry(QtCore.QRect(200, 430, 81, 23))
        self.SetMWfrequency.setFlat(False)
        self.SetMWfrequency.setObjectName("SetMWfrequency")
        self.MWpower = QtGui.QDoubleSpinBox(Panel)
        self.MWpower.setEnabled(False)
        self.MWpower.setGeometry(QtCore.QRect(100, 460, 81, 22))
        self.MWpower.setMinimum(-145.0)
        self.MWpower.setMaximum(30.0)
        self.MWpower.setSingleStep(0.1)
        self.MWpower.setProperty("value", 10.0)
        self.MWpower.setObjectName("MWpower")
        self.SetMWpower = QtGui.QPushButton(Panel)
        self.SetMWpower.setEnabled(False)
        self.SetMWpower.setGeometry(QtCore.QRect(200, 460, 81, 23))
        self.SetMWpower.setFlat(False)
        self.SetMWpower.setObjectName("SetMWpower")
        self.label_40 = QtGui.QLabel(Panel)
        self.label_40.setGeometry(QtCore.QRect(10, 460, 81, 16))
        self.label_40.setObjectName("label_40")
        self.label_30 = QtGui.QLabel(Panel)
        self.label_30.setGeometry(QtCore.QRect(330, 267, 81, 16))
        self.label_30.setObjectName("label_30")
        self.ModPeriod = QtGui.QSpinBox(Panel)
        self.ModPeriod.setEnabled(False)
        self.ModPeriod.setGeometry(QtCore.QRect(430, 263, 81, 22))
        self.ModPeriod.setMinimum(1)
        self.ModPeriod.setMaximum(1000000)
        self.ModPeriod.setProperty("value", 1000)
        self.ModPeriod.setObjectName("ModPeriod")

        self.retranslateUi(Panel)
        QtCore.QMetaObject.connectSlotsByName(Panel)

    def retranslateUi(self, Panel):
        Panel.setWindowTitle(QtGui.QApplication.translate("Panel", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Panel", "abs. laser frequency (GHz)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Panel", "reference offset (GHz)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Panel", "rel. laser frequency (GHz)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Panel", "rel. frequency setpoint (GHz)", None, QtGui.QApplication.UnicodeUTF8))
        self.StepUp.setText(QtGui.QApplication.translate("Panel", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.StepDown.setText(QtGui.QApplication.translate("Panel", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Panel", "step frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Panel", "MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.LockFrequency.setText(QtGui.QApplication.translate("Panel", "lock frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.LaserOn.setText(QtGui.QApplication.translate("Panel", "Laser on", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Panel", "scan repetitions", None, QtGui.QApplication.UnicodeUTF8))
        self.DCStarkShiftSweep.setText(QtGui.QApplication.translate("Panel", "DC Stark tuning", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Panel", "gate #", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Panel", "U start (V)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Panel", "U step (V)", None, QtGui.QApplication.UnicodeUTF8))
        self.LaserInitialize.setText(QtGui.QApplication.translate("Panel", "initialize laser before scan", None, QtGui.QApplication.UnicodeUTF8))
        self.PulseAOM.setText(QtGui.QApplication.translate("Panel", "pulse AOM", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Panel", "pulse duration (µs)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Panel", "power pulse (µW)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Panel", "power scan (µW)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Panel", "U stop (V)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Panel", "initial wait time (s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Panel", "U start (V)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Panel", "U step (V)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Panel", "(ca. 10 MHz / mV)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Panel", "step time (ms)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Panel", "wavemeter channel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Panel", "counter channel", None, QtGui.QApplication.UnicodeUTF8))
        self.ScanBack.setText(QtGui.QApplication.translate("Panel", "scan back laser", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Panel", "scan back time (s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Panel", "frequency averaging", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Panel", "interpolation step (MHz)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Panel", "mode hop threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.StartScan.setText(QtGui.QApplication.translate("Panel", "Start scan", None, QtGui.QApplication.UnicodeUTF8))
        self.AbortScan.setText(QtGui.QApplication.translate("Panel", "Abort scan", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("Panel", "piezo voltage", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("Panel", "scan voltage", None, QtGui.QApplication.UnicodeUTF8))
        self.SetPiezoVoltage.setText(QtGui.QApplication.translate("Panel", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.SetScanVoltage.setText(QtGui.QApplication.translate("Panel", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("Panel", "lock frequency deviation (MHz)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("Panel", "gate1 voltage", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("Panel", "gate2 voltage", None, QtGui.QApplication.UnicodeUTF8))
        self.SetGate1Voltage.setText(QtGui.QApplication.translate("Panel", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.SetGate2Voltage.setText(QtGui.QApplication.translate("Panel", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_999.setText(QtGui.QApplication.translate("Panel", "scan steps", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("Panel", "Comments", None, QtGui.QApplication.UnicodeUTF8))
        self.PauseScan.setText(QtGui.QApplication.translate("Panel", "Pause scan", None, QtGui.QApplication.UnicodeUTF8))
        self.GateSweep.setText(QtGui.QApplication.translate("Panel", "gate sweep", None, QtGui.QApplication.UnicodeUTF8))
        self.ModulateGate.setText(QtGui.QApplication.translate("Panel", "gate modulation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("Panel", "scan ctr. (GHz)", None, QtGui.QApplication.UnicodeUTF8))
        self.SetScanRangeCenter.setText(QtGui.QApplication.translate("Panel", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Panel", "current scan", None, QtGui.QApplication.UnicodeUTF8))
        self.PulseAOM_manual.setText(QtGui.QApplication.translate("Panel", "pulse AOM", None, QtGui.QApplication.UnicodeUTF8))
        self.SkipToNext.setText(QtGui.QApplication.translate("Panel", "skip to next scan", None, QtGui.QApplication.UnicodeUTF8))
        self.AutoOptimizeXY.setText(QtGui.QApplication.translate("Panel", "auto-optimize XY", None, QtGui.QApplication.UnicodeUTF8))
        self.AutoOptimizeZ.setText(QtGui.QApplication.translate("Panel", "auto-optimize Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("Panel", "opt. interval", None, QtGui.QApplication.UnicodeUTF8))
        self.MWOn.setText(QtGui.QApplication.translate("Panel", "MW on", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("Panel", "power after scan (µW)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("Panel", "MW freq. (GHz)", None, QtGui.QApplication.UnicodeUTF8))
        self.SetMWfrequency.setText(QtGui.QApplication.translate("Panel", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.SetMWpower.setText(QtGui.QApplication.translate("Panel", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("Panel", "MW power (dBm)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("Panel", "mod. period (µs)", None, QtGui.QApplication.UnicodeUTF8))

# from chaco_plot.time_trace_plot import TimeTracePlot
