# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer\optimize1d_panel.ui'
#
# Created: Wed Aug 17 16:13:53 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Panel(object):
    def setupUi(self, Panel):
        Panel.setObjectName("Panel")
        Panel.resize(261, 311)
        self.gridLayout_2 = QtGui.QGridLayout(Panel)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtGui.QLabel(Panel)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.scan_length = QtGui.QDoubleSpinBox(Panel)
        self.scan_length.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.scan_length.setObjectName("scan_length")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.scan_length)
        self.label_2 = QtGui.QLabel(Panel)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.pixel_time = QtGui.QSpinBox(Panel)
        self.pixel_time.setMaximum(10000)
        self.pixel_time.setObjectName("pixel_time")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.pixel_time)
        self.label_3 = QtGui.QLabel(Panel)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.nr_of_points = QtGui.QSpinBox(Panel)
        self.nr_of_points.setObjectName("nr_of_points")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.nr_of_points)
        self.gridLayout_2.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtGui.QLabel(Panel)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.counter = QtGui.QSpinBox(Panel)
        self.counter.setObjectName("counter")
        self.gridLayout.addWidget(self.counter, 0, 1, 1, 1)
        self.gaussian_fit = QtGui.QCheckBox(Panel)
        self.gaussian_fit.setObjectName("gaussian_fit")
        self.gridLayout.addWidget(self.gaussian_fit, 1, 0, 1, 2)
        self.start = QtGui.QPushButton(Panel)
        self.start.setObjectName("start")
        self.gridLayout.addWidget(self.start, 2, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.plot = LinePlot(Panel)
        self.plot.setMinimumSize(QtCore.QSize(200, 100))
        self.plot.setObjectName("plot")
        self.gridLayout_2.addWidget(self.plot, 1, 0, 1, 2)
        self.groupBox = QtGui.QGroupBox(Panel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.amplitude = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.amplitude.setFont(font)
        self.amplitude.setFrameShape(QtGui.QFrame.Box)
        self.amplitude.setObjectName("amplitude")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.amplitude)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.offset = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.offset.setFont(font)
        self.offset.setFrameShape(QtGui.QFrame.Box)
        self.offset.setObjectName("offset")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.offset)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.sigma = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.sigma.setFont(font)
        self.sigma.setFrameShape(QtGui.QFrame.Box)
        self.sigma.setObjectName("sigma")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.sigma)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_8)
        self.mu = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.mu.setFont(font)
        self.mu.setFrameShape(QtGui.QFrame.Box)
        self.mu.setObjectName("mu")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.mu)
        self.gridLayout_2.addWidget(self.groupBox, 2, 0, 1, 2)
        self.label.setBuddy(self.scan_length)
        self.label_2.setBuddy(self.pixel_time)
        self.label_3.setBuddy(self.nr_of_points)
        self.label_5.setBuddy(self.counter)

        self.retranslateUi(Panel)
        QtCore.QMetaObject.connectSlotsByName(Panel)

    def retranslateUi(self, Panel):
        Panel.setWindowTitle(QtGui.QApplication.translate("Panel", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Panel", "scan length [um]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Panel", "px time [ms]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Panel", "# points", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Panel", "counter", None, QtGui.QApplication.UnicodeUTF8))
        self.gaussian_fit.setText(QtGui.QApplication.translate("Panel", "gaussian fit?", None, QtGui.QApplication.UnicodeUTF8))
        self.start.setText(QtGui.QApplication.translate("Panel", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Panel", "fit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Panel", "Amplitude", None, QtGui.QApplication.UnicodeUTF8))
        self.amplitude.setText(QtGui.QApplication.translate("Panel", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Panel", "Offset", None, QtGui.QApplication.UnicodeUTF8))
        self.offset.setText(QtGui.QApplication.translate("Panel", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Panel", "sigma", None, QtGui.QApplication.UnicodeUTF8))
        self.sigma.setText(QtGui.QApplication.translate("Panel", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Panel", "mu", None, QtGui.QApplication.UnicodeUTF8))
        self.mu.setText(QtGui.QApplication.translate("Panel", "-", None, QtGui.QApplication.UnicodeUTF8))

from plots.chaco_plot import LinePlot
