# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/rt2_coordinator.ui'
#
# Created: Fri Mar 25 13:05:30 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Panel(object):
    def setupUi(self, Panel):
        Panel.setObjectName("Panel")
        Panel.resize(440, 719)
        Panel.setToolTip("None")
        Panel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.gridLayout_10 = QtGui.QGridLayout(Panel)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_3 = QtGui.QLabel(Panel)
        self.label_3.setObjectName("label_3")
        self.gridLayout_10.addWidget(self.label_3, 0, 0, 1, 1)
        self.keyword = QtGui.QLineEdit(Panel)
        self.keyword.setObjectName("keyword")
        self.gridLayout_10.addWidget(self.keyword, 0, 1, 1, 3)
        self.groupBox = QtGui.QGroupBox(Panel)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.stage_x = QtGui.QDoubleSpinBox(self.groupBox)
        self.stage_x.setEnabled(True)
        self.stage_x.setMinimum(-100.0)
        self.stage_x.setMaximum(100.0)
        self.stage_x.setSingleStep(0.2)
        self.stage_x.setObjectName("stage_x")
        self.gridLayout.addWidget(self.stage_x, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.stage_y = QtGui.QDoubleSpinBox(self.groupBox)
        self.stage_y.setEnabled(True)
        self.stage_y.setDecimals(2)
        self.stage_y.setMinimum(-100.0)
        self.stage_y.setMaximum(100.0)
        self.stage_y.setSingleStep(0.2)
        self.stage_y.setObjectName("stage_y")
        self.gridLayout.addWidget(self.stage_y, 1, 1, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox, 1, 0, 1, 2)
        self.groupBox_3 = QtGui.QGroupBox(Panel)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.front_z = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.front_z.setMaximum(100.0)
        self.front_z.setSingleStep(0.2)
        self.front_z.setObjectName("front_z")
        self.gridLayout_3.addWidget(self.front_z, 0, 0, 1, 1)
        self.front_z_slider = QtGui.QSlider(self.groupBox_3)
        self.front_z_slider.setMaximum(1000)
        self.front_z_slider.setSingleStep(1)
        self.front_z_slider.setPageStep(100)
        self.front_z_slider.setProperty("value", 500)
        self.front_z_slider.setOrientation(QtCore.Qt.Vertical)
        self.front_z_slider.setInvertedAppearance(False)
        self.front_z_slider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.front_z_slider.setTickInterval(20)
        self.front_z_slider.setObjectName("front_z_slider")
        self.gridLayout_3.addWidget(self.front_z_slider, 1, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_3, 1, 2, 8, 1)
        self.groupBox_4 = QtGui.QGroupBox(Panel)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.back_z = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.back_z.setMaximum(100.0)
        self.back_z.setSingleStep(0.2)
        self.back_z.setObjectName("back_z")
        self.gridLayout_4.addWidget(self.back_z, 0, 0, 1, 1)
        self.back_z_slider = QtGui.QSlider(self.groupBox_4)
        self.back_z_slider.setMaximum(1000)
        self.back_z_slider.setSingleStep(1)
        self.back_z_slider.setPageStep(100)
        self.back_z_slider.setProperty("value", 500)
        self.back_z_slider.setOrientation(QtCore.Qt.Vertical)
        self.back_z_slider.setInvertedAppearance(False)
        self.back_z_slider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.back_z_slider.setTickInterval(20)
        self.back_z_slider.setObjectName("back_z_slider")
        self.gridLayout_4.addWidget(self.back_z_slider, 1, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_4, 1, 3, 8, 1)
        self.groupBox_5 = QtGui.QGroupBox(Panel)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem = QtGui.QSpacerItem(72, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 0, 1, 1)
        self.stage_step_up = QtGui.QPushButton(self.groupBox_5)
        self.stage_step_up.setObjectName("stage_step_up")
        self.gridLayout_5.addWidget(self.stage_step_up, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(72, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 2, 1, 1)
        self.stage_step_left = QtGui.QPushButton(self.groupBox_5)
        self.stage_step_left.setObjectName("stage_step_left")
        self.gridLayout_5.addWidget(self.stage_step_left, 1, 0, 1, 1)
        self.stage_step = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.stage_step.setDecimals(1)
        self.stage_step.setSingleStep(0.1)
        self.stage_step.setProperty("value", 1.0)
        self.stage_step.setObjectName("stage_step")
        self.gridLayout_5.addWidget(self.stage_step, 1, 1, 1, 1)
        self.stage_step_right = QtGui.QPushButton(self.groupBox_5)
        self.stage_step_right.setObjectName("stage_step_right")
        self.gridLayout_5.addWidget(self.stage_step_right, 1, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(72, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 2, 0, 1, 1)
        self.stage_step_down = QtGui.QPushButton(self.groupBox_5)
        self.stage_step_down.setObjectName("stage_step_down")
        self.gridLayout_5.addWidget(self.stage_step_down, 2, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(72, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 2, 2, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_5, 2, 0, 1, 2)
        self.groupBox_7 = QtGui.QGroupBox(Panel)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_4 = QtGui.QLabel(self.groupBox_7)
        self.label_4.setObjectName("label_4")
        self.gridLayout_7.addWidget(self.label_4, 0, 0, 1, 1)
        self.back_x = QtGui.QDoubleSpinBox(self.groupBox_7)
        self.back_x.setEnabled(True)
        self.back_x.setMinimum(-100.0)
        self.back_x.setMaximum(100.0)
        self.back_x.setSingleStep(0.2)
        self.back_x.setObjectName("back_x")
        self.gridLayout_7.addWidget(self.back_x, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_7)
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 1, 0, 1, 1)
        self.back_y = QtGui.QDoubleSpinBox(self.groupBox_7)
        self.back_y.setEnabled(True)
        self.back_y.setDecimals(2)
        self.back_y.setMinimum(-100.0)
        self.back_y.setMaximum(100.0)
        self.back_y.setSingleStep(0.2)
        self.back_y.setObjectName("back_y")
        self.gridLayout_7.addWidget(self.back_y, 1, 1, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_7, 3, 0, 1, 2)
        self.groupBox_6 = QtGui.QGroupBox(Panel)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem4, 0, 0, 1, 1)
        self.back_step_up = QtGui.QPushButton(self.groupBox_6)
        self.back_step_up.setObjectName("back_step_up")
        self.gridLayout_6.addWidget(self.back_step_up, 0, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem5, 0, 2, 1, 1)
        self.back_step_left = QtGui.QPushButton(self.groupBox_6)
        self.back_step_left.setObjectName("back_step_left")
        self.gridLayout_6.addWidget(self.back_step_left, 1, 0, 1, 1)
        self.back_step = QtGui.QDoubleSpinBox(self.groupBox_6)
        self.back_step.setDecimals(1)
        self.back_step.setSingleStep(0.1)
        self.back_step.setProperty("value", 1.0)
        self.back_step.setObjectName("back_step")
        self.gridLayout_6.addWidget(self.back_step, 1, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem6, 2, 0, 1, 1)
        self.back_step_down = QtGui.QPushButton(self.groupBox_6)
        self.back_step_down.setObjectName("back_step_down")
        self.gridLayout_6.addWidget(self.back_step_down, 2, 1, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem7, 2, 2, 1, 1)
        self.back_step_right = QtGui.QPushButton(self.groupBox_6)
        self.back_step_right.setObjectName("back_step_right")
        self.gridLayout_6.addWidget(self.back_step_right, 1, 2, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_6, 4, 0, 1, 2)
        self.groupBox_8 = QtGui.QGroupBox(Panel)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_6 = QtGui.QLabel(self.groupBox_8)
        self.label_6.setObjectName("label_6")
        self.gridLayout_8.addWidget(self.label_6, 0, 0, 1, 1)
        self.detsm_x = QtGui.QDoubleSpinBox(self.groupBox_8)
        self.detsm_x.setEnabled(True)
        self.detsm_x.setMinimum(-100.0)
        self.detsm_x.setMaximum(100.0)
        self.detsm_x.setSingleStep(0.2)
        self.detsm_x.setObjectName("detsm_x")
        self.gridLayout_8.addWidget(self.detsm_x, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_8)
        self.label_7.setObjectName("label_7")
        self.gridLayout_8.addWidget(self.label_7, 1, 0, 1, 1)
        self.detsm_y = QtGui.QDoubleSpinBox(self.groupBox_8)
        self.detsm_y.setEnabled(True)
        self.detsm_y.setDecimals(2)
        self.detsm_y.setMinimum(-100.0)
        self.detsm_y.setMaximum(100.0)
        self.detsm_y.setSingleStep(0.2)
        self.detsm_y.setObjectName("detsm_y")
        self.gridLayout_8.addWidget(self.detsm_y, 1, 1, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_8, 5, 0, 1, 2)
        self.groupBox_2 = QtGui.QGroupBox(Panel)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.toggle_bs_spectrometer = QtGui.QPushButton(self.groupBox_2)
        self.toggle_bs_spectrometer.setToolTip("None")
        self.toggle_bs_spectrometer.setFlat(False)
        self.toggle_bs_spectrometer.setObjectName("toggle_bs_spectrometer")
        self.gridLayout_2.addWidget(self.toggle_bs_spectrometer, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_2, 6, 0, 1, 2)
        self.groupBox_9 = QtGui.QGroupBox(Panel)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.toggle_bs_rear_det = QtGui.QPushButton(self.groupBox_9)
        self.toggle_bs_rear_det.setToolTip("None")
        self.toggle_bs_rear_det.setFlat(False)
        self.toggle_bs_rear_det.setObjectName("toggle_bs_rear_det")
        self.gridLayout_9.addWidget(self.toggle_bs_rear_det, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_9, 8, 0, 1, 2)
        self.groupBox_10 = QtGui.QGroupBox(Panel)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBox_10)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.toggle_bs_pulsed_laser = QtGui.QPushButton(self.groupBox_10)
        self.toggle_bs_pulsed_laser.setToolTip("None")
        self.toggle_bs_pulsed_laser.setFlat(False)
        self.toggle_bs_pulsed_laser.setObjectName("toggle_bs_pulsed_laser")
        self.gridLayout_11.addWidget(self.toggle_bs_pulsed_laser, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_10, 7, 0, 1, 2)

        self.retranslateUi(Panel)
        QtCore.QObject.connect(self.stage_x, QtCore.SIGNAL("editingFinished()"), Panel.new_stage_x)
        QtCore.QObject.connect(self.stage_y, QtCore.SIGNAL("editingFinished()"), Panel.new_stage_y)
        QtCore.QObject.connect(self.front_z_slider, QtCore.SIGNAL("sliderMoved(int)"), Panel.slide_front_z)
        QtCore.QObject.connect(self.front_z, QtCore.SIGNAL("editingFinished()"), Panel.new_front_z)
        QtCore.QObject.connect(Panel, QtCore.SIGNAL("front_z_slide_changed(int)"), self.front_z_slider.setValue)
        QtCore.QObject.connect(Panel, QtCore.SIGNAL("front_z_changed(double)"), self.front_z.setValue)
        QtCore.QObject.connect(Panel, QtCore.SIGNAL("stage_x_changed(double)"), self.stage_x.setValue)
        QtCore.QObject.connect(Panel, QtCore.SIGNAL("stage_y_changed(double)"), self.stage_y.setValue)
        QtCore.QObject.connect(self.toggle_bs_spectrometer, QtCore.SIGNAL("clicked()"), Panel.toggle_spectrometer_bs)
        QtCore.QObject.connect(self.keyword, QtCore.SIGNAL("textEdited(QString)"), Panel.set_keyword)
        QtCore.QObject.connect(self.stage_step_left, QtCore.SIGNAL("clicked()"), Panel.stage_left)
        QtCore.QObject.connect(self.stage_step_up, QtCore.SIGNAL("clicked()"), Panel.stage_up)
        QtCore.QObject.connect(self.stage_step_right, QtCore.SIGNAL("clicked()"), Panel.stage_right)
        QtCore.QObject.connect(self.stage_step_down, QtCore.SIGNAL("clicked()"), Panel.stage_down)
        QtCore.QObject.connect(self.back_x, QtCore.SIGNAL("editingFinished()"), Panel.new_back_x)
        QtCore.QObject.connect(self.back_y, QtCore.SIGNAL("editingFinished()"), Panel.new_back_y)
        QtCore.QObject.connect(Panel, QtCore.SIGNAL("back_x_changed(double)"), self.back_x.setValue)
        QtCore.QObject.connect(Panel, QtCore.SIGNAL("back_y_changed(double)"), self.back_y.setValue)
        QtCore.QObject.connect(self.back_step_left, QtCore.SIGNAL("clicked()"), Panel.back_left)
        QtCore.QObject.connect(self.back_step_up, QtCore.SIGNAL("clicked()"), Panel.back_up)
        QtCore.QObject.connect(self.back_step_right, QtCore.SIGNAL("clicked()"), Panel.back_right)
        QtCore.QObject.connect(self.back_step_down, QtCore.SIGNAL("clicked()"), Panel.back_down)
        QtCore.QObject.connect(self.detsm_x, QtCore.SIGNAL("editingFinished()"), Panel.new_detsm_x)
        QtCore.QObject.connect(self.detsm_y, QtCore.SIGNAL("editingFinished()"), Panel.new_detsm_y)
        QtCore.QObject.connect(Panel, QtCore.SIGNAL("detsm_x_changed(double)"), self.detsm_x.setValue)
        QtCore.QObject.connect(Panel, QtCore.SIGNAL("detsm_y_changed(double)"), self.detsm_y.setValue)
        QtCore.QObject.connect(self.toggle_bs_rear_det, QtCore.SIGNAL("clicked()"), Panel.toggle_rear_det_bs)
        QtCore.QObject.connect(self.back_z_slider, QtCore.SIGNAL("sliderMoved(int)"), Panel.slide_back_z)
        QtCore.QObject.connect(Panel, QtCore.SIGNAL("back_z_slide_changed(int)"), self.back_z_slider.setValue)
        QtCore.QObject.connect(self.back_z, QtCore.SIGNAL("editingFinished()"), Panel.new_back_z)
        QtCore.QObject.connect(Panel, QtCore.SIGNAL("back_z_changed(double)"), self.back_z.setValue)
        QtCore.QObject.connect(Panel, QtCore.SIGNAL("keyword_changed(QString)"), self.keyword.setText)
        QtCore.QObject.connect(self.toggle_bs_pulsed_laser, QtCore.SIGNAL("clicked()"), Panel.toggle_pulsed_laser_bs)
        QtCore.QMetaObject.connectSlotsByName(Panel)

    def retranslateUi(self, Panel):
        Panel.setWindowTitle(QtGui.QApplication.translate("Panel", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Panel", "Keyword", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Panel", "Stage position", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Panel", "x [um]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Panel", "y [um]", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Panel", "Front z [um]", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Panel", "Back z [um]", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Panel", "Stage step [um]", None, QtGui.QApplication.UnicodeUTF8))
        self.stage_step_up.setText(QtGui.QApplication.translate("Panel", "up", None, QtGui.QApplication.UnicodeUTF8))
        self.stage_step_left.setText(QtGui.QApplication.translate("Panel", "left", None, QtGui.QApplication.UnicodeUTF8))
        self.stage_step_right.setText(QtGui.QApplication.translate("Panel", "right", None, QtGui.QApplication.UnicodeUTF8))
        self.stage_step_down.setText(QtGui.QApplication.translate("Panel", "down", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("Panel", "Back SM position", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Panel", "x [um]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Panel", "y [um]", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("Panel", "Back SM step [um]", None, QtGui.QApplication.UnicodeUTF8))
        self.back_step_up.setText(QtGui.QApplication.translate("Panel", "up", None, QtGui.QApplication.UnicodeUTF8))
        self.back_step_left.setText(QtGui.QApplication.translate("Panel", "left", None, QtGui.QApplication.UnicodeUTF8))
        self.back_step_down.setText(QtGui.QApplication.translate("Panel", "down", None, QtGui.QApplication.UnicodeUTF8))
        self.back_step_right.setText(QtGui.QApplication.translate("Panel", "right", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("Panel", "Det SM position", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Panel", "x [um]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Panel", "y [um]", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Panel", "BS: Spectrometer", None, QtGui.QApplication.UnicodeUTF8))
        self.toggle_bs_spectrometer.setText(QtGui.QApplication.translate("Panel", "Toggle", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("Panel", "BS: Rear detection path", None, QtGui.QApplication.UnicodeUTF8))
        self.toggle_bs_rear_det.setText(QtGui.QApplication.translate("Panel", "Toggle", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("Panel", "BS: Pulsed Laser", None, QtGui.QApplication.UnicodeUTF8))
        self.toggle_bs_pulsed_laser.setText(QtGui.QApplication.translate("Panel", "Toggle", None, QtGui.QApplication.UnicodeUTF8))

