ZPLServo.move_in()
ZPLServo_lt1.move_in()
qt.msleep(2)
NewfocusAOM_lt1.set_power(2e-9)
NewfocusAOM.set_power(.2e-9)
qt.msleep(2)
print 'Both in:', adwin.get_countrates()
NewfocusAOM_lt1.set_power(0e-9)
NewfocusAOM.set_power(0e-9)
qt.msleep(2)

ZPLServo.move_in()
ZPLServo_lt1.move_out()
qt.msleep(2)
NewfocusAOM_lt1.set_power(2e-9)
qt.msleep(2)
print 'LT1 out, nf lt1:', adwin.get_countrates()
NewfocusAOM_lt1.set_power(0e-9)
qt.msleep(2)

ZPLServo.move_in()
ZPLServo_lt1.move_out()
qt.msleep(2)
NewfocusAOM.set_power(2e-9)
qt.msleep(2)
print 'LT1 out, nf lt2:', adwin.get_countrates()
NewfocusAOM.set_power(0e-9)
qt.msleep(2)


ZPLServo.move_out()
ZPLServo_lt1.move_in()
qt.msleep(2)
NewfocusAOM.set_power(.2e-9)
qt.msleep(2)
print 'lt2 out, nf lt2:', adwin.get_countrates()
NewfocusAOM.set_power(0e-9)
qt.msleep(2)

ZPLServo.move_out()
ZPLServo_lt1.move_in()
qt.msleep(2)
NewfocusAOM_lt1.set_power(.2e-9)
qt.msleep(2)
print 'lt2 out, nf lt1:', adwin.get_countrates()
NewfocusAOM_lt1.set_power(0e-9)
qt.msleep(2)

ZPLServo.move_in()
ZPLServo_lt1.move_in()
