'<ADbasic Header, Headerversion 001.001>
'<Header End>
'  slot	 module    description	address	tico
'    1   CPU T11   Processor    -	      -
'    2   CNT-T     4 Counters   1       Yes
'    3   CIO 32    32 TTL DIOs  2       Yes
'    4   AIN 32/18 18bit ADC    3
'    5   AOUT 8/16 16bit DACs   4

#DEFINE CTR_MODULE 1  'Address of CNT-T
#DEFINE DIO_MODULE 2  'Address of DIO 32
#DEFINE ADC_MODULE 3  'Address of AIN 32/18
#DEFINE DAC_MODULE 4  'Address of AOUT 8/16

