config = {}

config['adwin_lt2_dacs'] = {
        'atto_x' : 1,
        'atto_y' : 2,
        'atto_z' : 3,
        'yellow_aom_frq' : 4,
        'yellow_aom' : 5,
        'matisse_aom' : 6,
        'green_aom': 7,
        'newfocus_aom' : 8,
        }

config['adwin_lt2_dios'] = {

        }

config['adwin_lt2_processes'] = {
        
        'linescan' : {
        
            'index' : 2, 
            'file' : 'lt2_linescan.TB2',
            'par' : {
                'set_cnt_dacs' : 1,
                'set_steps' : 2,
                'set_px_action' : 3,
                'get_px_clock' : 4,
                'set_phase_locking_on' : 19,
                'set_gate_good_phase' : 18,
                },
            'fpar' : {
                'set_px_time' : 1,
                'supplemental_data_input' : 2,
                'simple_counting' : 3,  # 1 for simple, 0 for resonant counting
                },
            'data_long' : {
                'set_dac_numbers' : 200,
                'get_counts' : [11,12,13],
                },
            'data_float' : {
                'set_start_voltages' : 199,
                'set_stop_voltages' : 198,
                'get_supplemental_data' : 15,
                },
            },
        
        'counter' : {
            'doc' : '',
            'info' : {
                'counters' : 4,
                },
            'index' : 1, 
            'file' : 'simple_counting.TB1',
            'par' : {
                'set_integration_time' : 23,
                'set_avg_periods' : 24,
                'set_single_run' : 25,
                'get_countrates' : [41, 42, 43, 44],
                },
            'data_long' : {
                'get_last_counts' : 45,
                },
            },

        'resonant_counting' : {
            'doc' : '',
            'index' : 1,
            'file' : 'resonant_counting.TB1',
            'par' : {
                'set_aom_dac' : 26,
                'set_aom_duration' : 27,
                'set_probe_duration' : 28,
                'set_gate_dac': 12, 
                },
            'fpar' : {
                'set_aom_voltage' : 30,
                'floating_average': 11, #floating average time (ms)
                'gate_voltage' : 12,
                },
            'data_float' : {
                'get_counts' : [41,42,43,44],
                },
            },
        
        'set_dac' :  {
            'index' : 3, 
            'file' : 'SetDac.TB3',
            'par' : {
                'dac_no' : 20,
                },
            'fpar' : {
                'dac_voltage' : 20,
                },
            },
        
        'set_dio' :  {
            'index' : 4, 
            'file' : 'Set_TTL_Outputs_LTsetup2.TB4',
            'par' : {
                'dio_no' : 61, #configured DIO 08:15 as input, all other ports as output
                'dio_val' : 62,
                },
            },
         
        'init_data' :  {
            'index' : 5, 
            'file' : 'init_data.TB5',
            },
         
        # FIXME what does that do? still needed? name!?
        'DIO_test' :  {
            'index' : 6, 
            'file' : 'universalDI.TB6',
            'par' : {
                'output' : 65,
                'edge' : 66,
                },
            },

        # FIXME what does that do? still needed? name!?
        'universal_dac' : {
                'index' : 6,
                'file' : 'universalDAC.tb6', 
                },
        
        # ADwin single-shot readout
        'singleshot' : {
                'index' : 9,
                'file' : 'singleshot_lt2.TB9',
                'params_long' : [           # keep order!!!!!!!!!!!!!
                    ['counter_channel'             ,   1],
                    ['repump_laser_DAC_channel'    ,   7],
                    ['Ex_laser_DAC_channel'        ,   6],
                    ['A_laser_DAC_channel'         ,   8],
                    ['AWG_start_DO_channel'        ,  16],
                    ['AWG_done_DI_channel'         ,   8],
                    ['send_AWG_start'              ,   0],
                    ['wait_for_AWG_done'           ,   0],
                    ['repump_duration'             ,   5],
                    ['CR_duration'                 ,  50],
                    ['SP_duration'                 , 100],
                    ['SP_filter_duration'          ,   0],
                    ['sequence_wait_time'          ,   0],
                    ['wait_after_pulse_duration'   ,   1],
                    ['CR_preselect'                ,  10],
                    ['SSRO_repetitions'            ,1000],
                    ['SSRO_duration'               ,  50],
                    ['SSRO_stop_after_first_photon',   0],
                    ['cycle_duration'              , 300],
                    ['CR_probe'                    ,  10],
                    ['repump_after_repetitions'    ,  1],
                    ['CR_repump'                   ,  0],
                    ],
                'params_long_index'  : 20,
                'params_long_length' : 25,
                'params_float' : [
                    ['repump_voltage' , 0.8],
                    ['repump_off_voltage'   , 0.07],
                    ['Ex_CR_voltage'        , 0.8],
                    ['A_CR_voltage'         , 0.8],
                    ['Ex_SP_voltage'        , 0.8],
                    ['A_SP_voltage'         , 0.8],
                    ['Ex_RO_voltage'        , 0.8],
                    ['A_RO_voltage'         , 0.8],
                    ['Ex_off_voltage'       , 0.0],
                    ['A_off_voltage'        , -0.08]
                    ],
                'params_float_index'  : 21,
                'params_float_length' : 15,
                'par' : {
                    'completed_reps' : 73,
                    'total_CR_counts' : 70,
                    'CR_threshold' : 25,
                    'last_CR_counts' : 26,
                    },
				'data_long' : {
                    'CR_before' : 22,
                    'CR_after' : 23,
                    'SP_hist' : 24,
                    'RO_data' : 25,
                    'statistics' : 26,
                    }, 
                },
        
                # ADwin single-shot readout with yellow freq aom scan
        
        'singleshot_yellow_scan' : {
                'index' : 9,
                'file' : 'singleshot_lt2_ys.TB9',
                'params_long' : [           # keep order!!!!!!!!!!!!!
                    ['counter_channel'             ,   1],
                    ['repump_laser_DAC_channel'    ,   7],
                    ['Ex_laser_DAC_channel'        ,   6],
                    ['A_laser_DAC_channel'         ,   8],
                    ['AWG_start_DO_channel'        ,  16],
                    ['AWG_done_DI_channel'         ,   8],
                    ['send_AWG_start'              ,   0],
                    ['wait_for_AWG_done'           ,   0],
                    ['repump_duration'             ,   5],
                    ['CR_duration'                 ,  50],
                    ['SP_duration'                 , 100],
                    ['SP_filter_duration'          ,   0],
                    ['sequence_wait_time'          ,   0],
                    ['wait_after_pulse_duration'   ,   1],
                    ['CR_preselect'                ,  10],
                    ['SSRO_repetitions'            ,1000],
                    ['SSRO_duration'               ,  50],
                    ['SSRO_stop_after_first_photon',   0],
                    ['cycle_duration'              , 300],
                    ['CR_probe'                    ,  10],
                    ['repump_after_repetitions'    ,  1],
                    ['CR_repump'                   ,  0],
                    ['freq_AOM_DAC_channel'        ,  4],
                    ],
                'params_long_index'  : 20,
                'params_long_length' : 25,
                'params_float' : [
                    ['repump_voltage' , 0.8],
                    ['repump_off_voltage'   , 0.04],
                    ['Ex_CR_voltage'        , 0.8],
                    ['A_CR_voltage'         , 0.8],
                    ['Ex_SP_voltage'        , 0.8],
                    ['A_SP_voltage'         , 0.8],
                    ['Ex_RO_voltage'        , 0.8],
                    ['A_RO_voltage'         , 0.8],
                    ['Ex_off_voltage'       , 0.0],
                    ['A_off_voltage'        , -0.08],
                    ['repump_freq_control_offset', 5.] 
                    ],
                'params_float_index'  : 21,
                'params_float_length' : 20,
                'par' : {
                    'completed_reps' : 73,
                    'total_CR_counts' : 70,
                    'CR_threshold' : 25,
                    'last_CR_counts' : 26,
                    },
                'data_float': {
                    'repump_freq_voltages'      : 19,
                    },
				'data_long' : {
                    'CR_before' : 22,
                    'CR_after' : 23,
                    'SP_hist' : 24,
                    'RO_data' : 25,
                    'statistics' : 26,
                    }, 
                },
        
        # ADwin conditional segmented SSRO
        'segmented_ssro' : {
                'index' : 9,
                'file' : 'ssro_segmented_RO_lt2.TB9',
                'params_long' : [           # keep order!!!!!!!!!!!!!
                    ['counter_channel'             ,   1],
                    ['laser_DAC_channel'    ,   7],
                    ['Ex_laser_DAC_channel'        ,   6],
                    ['A_laser_DAC_channel'         ,   8],
                    ['AWG_start_DO_channel'        ,  16],
                    ['AWG_done_DI_channel'         ,   8],
                    ['send_AWG_start'              ,   0],
                    ['wait_for_AWG_done'           ,   0],
                    ['repump_duration'             ,   5],
                    ['CR_duration'                 ,  50],
                    ['SP_duration'                 , 100],
                    ['SP_filter_duration'          ,   0],
                    ['sequence_wait_time'          ,   0],
                    ['wait_after_pulse_duration'   ,   1],
                    ['CR_preselect'                ,  10],
                    ['SSRO_repetitions'            ,1000],
                    ['SSRO_duration'               ,  50],
                    ['SSRO_stop_after_first_photon',   0],
                    ['cycle_duration'              , 300],
                    ['CR_probe'                    ,  10],
                    ['repump_after_repetitions'    ,  1],
                    ['CR_repump'                   ,  0],
                    ['segmented_RO_duration'        , 20],
                    ],
                'params_long_index'  : 20,
                'params_long_length' : 25,
                'params_float' : [
                    ['repump_voltage' , 0.8],
                    ['repump_off_voltage'   , 0.07],
                    ['Ex_CR_voltage'        , 0.8],
                    ['A_CR_voltage'         , 0.8],
                    ['Ex_SP_voltage'        , 0.8],
                    ['A_SP_voltage'         , 0.8],
                    ['Ex_RO_voltage'        , 0.8],
                    ['A_RO_voltage'         , 0.8],
                    ['Ex_off_voltage'       , 0.0],
                    ['A_off_voltage'        , -0.08],
                    ['segmented_Ex_RO_voltage',0.1]
                    ],
                'params_float_index'  : 21,
                'params_float_length' : 10,
                'par' : {
                    'completed_reps' : 73,
                    'total_CR_counts' : 70,
                    'CR_threshold' : 25,
                    'last_CR_counts' : 26,
                    },
				'data_long' : {
                    'CR_before' : 22,
                    'CR_after' : 23,
                    'SP_hist' : 24,
                    #'RO_data' : 25,
                    'statistics' : 26,
                    'segment_number' : 27,
                    'full_RO_data' : 28,
                    'segmented_RO_data' : 29,
                    }, 
                },
             
        # ADwin single-shot readout
        'integrated_ssro' : {
                'index' : 9,
                'file' : 'integrated_ssro_lt2.TB9',
                'params_long' : [           # keep order!!!!!!!!!!!!!
                    ['counter_channel'             ,   1],
                    ['repump_laser_DAC_channel'    ,   7],
                    ['Ex_laser_DAC_channel'        ,   6],
                    ['A_laser_DAC_channel'         ,   8],
                    ['AWG_start_DO_channel'        ,  16],
                    ['AWG_done_DI_channel'         ,   8],
                    ['send_AWG_start'              ,   0],
                    ['wait_for_AWG_done'           ,   0],
                    ['repump_duration'             ,   5],
                    ['CR_duration'                 ,  50],
                    ['SP_duration'                 , 100],
                    ['sweep_length'                ,   1],
                    ['sequence_wait_time'          ,   0],
                    ['wait_after_pulse_duration'   ,   1],
                    ['CR_preselect'                ,  10],
                    ['SSRO_repetitions'            ,1000],
                    ['SSRO_duration'               ,  50],
                    ['SSRO_stop_after_first_photon',   0],
                    ['cycle_duration'              , 300],
                    ['CR_probe'                    ,  10],
                    ['repump_after_repetitions'    ,  1],
                    ['CR_repump'                   ,  0],
                    ],
                'params_long_index'  : 20,
                'params_long_length' : 25,
                'params_float' : [
                    ['repump_voltage'       , 0.8],
                    ['repump_off_voltage'   , 0.07],
                    ['Ex_CR_voltage'        , 0.8],
                    ['A_CR_voltage'         , 0.8],
                    ['Ex_SP_voltage'        , 0.8],
                    ['A_SP_voltage'         , 0.8],
                    ['Ex_RO_voltage'        , 0.8],
                    ['A_RO_voltage'         , 0.8],
                    ['Ex_off_voltage'       , 0.0],
                    ['A_off_voltage'        , -0.08]
                    ],
                'params_float_index'  : 21,
                'params_float_length' : 10,
                'par' : {
                    'completed_reps' : 73,
                    'total_CR_counts' : 70,
                    'CR_events_below_threshold' : 71,
                    'CR_events' : 72,                    
                    'CR_threshold' : 25,
                    'last_CR_counts' : 26,
                    },
				'data_long' : {
                     'CR_before' : 22,  # not used in the integrated ssro
                     'CR_after' : 23,
                    'SP_hist' : 24,
                    'RO_data' : 25,
                    'statistics' : 26,
                    }, 
                },
        
        'MBI' : {
                'info' : """
                    Conditional repumping, and resonant readout at the end.
                    Has one MBI step and can read out multiple times (e.g., on different lines).
                    """,
                'index' : 9,
                'file' : 'lt2_MBI.TB9',
                'params_long' : [           # keep order!!!!!!!!!!!!!
                    ['counter_channel'             ,   1],
                    ['repump_laser_DAC_channel'    ,   4],
                    ['Ex_laser_DAC_channel'        ,   6],
                    ['A_laser_DAC_channel'         ,   8],
                    ['AWG_start_DO_channel'        ,   0],
                    ['AWG_done_DI_channel'         ,   9],
                    ['repump_duration'             ,   5],
                    ['CR_duration'                 ,  50],
                    ['SP_E_duration'               , 100],
                    ['wait_after_pulse_duration'   ,   1],
                    ['CR_preselect'                ,  10],
                    ['repetitions'                 ,1000],
                    ['sweep_length'                ,  10],
                    ['cycle_duration'              , 300],
                    ['CR_probe'                    ,  10],
                    ['AWG_event_jump_DO_channel'   ,   6],
                    ['MBI_duration'                ,   1],
                    ['MBI_steps'                   ,   1],
                    ['MBI_threshold'               ,   0],
                    ['nr_of_ROsequences'           ,   1],
                    ['wait_after_RO_pulse_duration',   3],
                    ['repump_after_repetitions'    ,   1],
                    ['CR_repump'                   ,   0],
                    ],
                'params_long_index'  : 20,
                'params_long_length' : 30,
                'params_float' : [
                    ['repump_voltage'       , 0.8],
                    ['repump_off_voltage'   , 0.0],
                    ['Ex_CR_voltage'        , 0.8],
                    ['A_CR_voltage'         , 0.8],
                    ['Ex_SP_voltage'        , 0.8],
                    ['Ex_MBI_voltage'       , 0.8],
                    ['Ex_off_voltage'       , 0.0],
                    ['A_off_voltage'        , -0.08]
                    ],
                'params_float_index'  : 21,
                'params_float_length' : 6,
                'par' : {
                    'CR_preselect' : 75,
                    'CR_probe' : 68,
                    'completed_reps' : 73,
                    },
                'data_long' : {
                    'CR_before' : 22,
                    'CR_after' : 23,
                    'MBI_attempts' : 24,
                    'MBI_cycles' : 25,
                    'statistics' : 26,
                    'ssro_results' : 27,
                    },
                },
                     
        'general_pulses_sweep' : { 
                'index' : 9,
                'file' : 'general_pulses_sweep.TB9',
                'params_long' : [           # keep order!!!!!!!!!!!!!
                    ['counter_channel'             ,   4],
                    ['dac1_channel'                ,   7],
                    ['dac2_channel'                ,   6],
                    ['dac3_channel'                ,   8],
                    ['max_element'                 ,   4],
                    ['cycle_duration'              , 300],
                    ['wait_after_pulse_duration'   ,   1],
                    ['max_sweep'                   ,  10],
                    ['sweep_channel'               ,   7],
                    ['do_sweep_duration'           ,   0],
                    ['sweep_element'               ,  10],
                    ],
                'params_long_index'  : 20,
                'params_long_length' : 11,
                'par' : {
                    'repetition_counter'      : 73,
                    'total_counts'            : 15,
                    },
                'data_float': {
                    'dac1_voltages'             : 21,
                    'dac2_voltages'             : 22,
                    'dac3_voltages'             : 23,
                    'sweep_voltages'            : 26,
                    },
                'data_long': {
                    'counter_on'                : 24,
                    'element_durations'         : 25,
                    'results'                   : 30,
                    'histogram'                 : 31,
                    'counter'                   : 32,
                    'sweep_durations'           : 27,
                    },
                },
       
        'general_pulses_repeat' : { 
                'index' : 9,
                'file' : 'general_pulses_repeat.TB9',
                'params_long' : [           # keep order!!!!!!!!!!!!!
                    ['counter_channel'             ,   4],
                    ['dac1_channel'                ,   7],
                    ['dac2_channel'                ,   6],
                    ['dac3_channel'                ,   8],
                    ['max_element'                 ,   4],
                    ['cycle_duration'              , 300],
                    ['wait_after_pulse_duration'   ,   1],
                    ['max_repetitions'             ,10000],
                    ['timed_element'               ,   1],
                    ],
                'params_long_index'  : 20,
                'params_long_length' : 11,
                'par' : {
                    'repetition_counter'      : 72,
                    'total_counts'            : 70,
                    },
                'data_float': {
                    'dac1_voltages'             : 21,
                    'dac2_voltages'             : 22,
                    'dac3_voltages'             : 23,
                    },
                'data_long': {
                    'counter_on'                : 24,
                    'element_durations'         : 25,
                    'results'                   : 30,
                    'histogram'                 : 31,
                    'first_count'               : 32,
                    },
                },
      
        'spincontrol' : {  #with conditional repump, resonant
                'index' : 9,
                'file' : 'spincontrol_lt2.TB9',
                'params_long' : [           # keep order!!!!!!!!!!!!!
                    ['counter_channel'             ,   1],
                    ['green_laser_DAC_channel'     ,   7],
                    ['Ex_laser_DAC_channel'        ,   6],
                    ['A_laser_DAC_channel'         ,   8],
                    ['AWG_start_DO_channel'        ,   1],
                    ['AWG_done_DI_channel'         ,   8],
                    ['send_AWG_start'              ,   0],
                    ['wait_for_AWG_done'           ,   0],
                    ['green_repump_duration'       ,   5],
                    ['CR_duration'                 ,  50],
                    ['SP_duration'                 , 100],
                    ['SP_filter_duration'          ,   0],
                    ['sequence_wait_time'          ,   0],
                    ['wait_after_pulse_duration'   ,   1],
                    ['CR_preselect'                ,  10],
                    ['RO_repetitions'              ,1000],
                    ['RO_duration'                 ,  50],
                    ['sweep_length'                ,  10],
                    ['cycle_duration'              , 300],
                    ],
                'params_long_index'  : 20,
                'params_long_length' : 25,
                'params_float' : [
                    ['green_repump_voltage' , 0.8],
                    ['green_off_voltage'    , 0.07],
                    ['Ex_CR_voltage'        , 0.8],
                    ['A_CR_voltage'         , 0.8],
                    ['Ex_SP_voltage'        , 0.8],
                    ['A_SP_voltage'         , 0.8],
                    ['Ex_RO_voltage'        , 0.8],
                    ['A_RO_voltage'         , 0.8],
                   ],
                'params_float_index'  : 21,
                'params_float_length' : 10,
                'par' : {
                    'set_phase_locking_on'      : 19,
                    'set_gate_good_phase'       : 18,}
                },

        'spincontrol_MBI' : {  #with conditional repump, resonant, MBI
                'index' : 9,
                'file' : 'MBI_spincontrol_lt2.TB9',
                'params_long' : [           # keep order!!!!!!!!!!!!!
                    ['counter_channel'             ,   1],
                    ['green_laser_DAC_channel'     ,   7],
                    ['Ex_laser_DAC_channel'        ,   6],
                    ['A_laser_DAC_channel'         ,   8],
                    ['AWG_start_DO_channel'        ,   1],
                    ['AWG_done_DI_channel'         ,   8],
                    ['send_AWG_start'              ,   0],
                    ['wait_for_AWG_done'           ,   0],
                    ['green_repump_duration'       ,   5],
                    ['CR_duration'                 ,  50],
                    ['SP_E_duration'                 , 100],
                    ['SP_filter_duration'          ,   0],
                    ['sequence_wait_time'          ,   0],
                    ['wait_after_pulse_duration'   ,   1],
                    ['CR_preselect'                ,  10],
                    ['RO_repetitions'              ,1000],
                    ['RO_duration'                 ,  50],
                    ['sweep_length'                ,  10],
                    ['cycle_duration'              , 300],
                    ['CR_probe'                    ,  10],
                    ['AWG_event_jump_DO_channel'   ,   6],
                    ['MBI_duration'                ,   1],
                    ['wait_for_MBI_pulse'          ,   4],
                    ['SP_A_duration'               , 300],
                    ['MBI_threshold'               , 0  ]
                    ],
                'params_long_index'  : 20,
                'params_long_length' : 25,
                'params_float' : [
                    ['green_repump_voltage' , 0.8],
                    ['green_off_voltage'    , 0.0],
                    ['Ex_CR_voltage'        , 0.8],
                    ['A_CR_voltage'         , 0.8],
                    ['Ex_SP_voltage'        , 0.8],
                    ['A_SP_voltage'         , 0.8],
                    ['Ex_RO_voltage'        , 0.8],
                    ['A_RO_voltage'         , 0.8]
                    ],
                'params_float_index'  : 21,
                'params_float_length' : 10,
                'par' : {
                    'set_phase_locking_on'      : 19,
                    'set_gate_good_phase'       : 18,}
                },
        
        'MBI_Multiple_RO' : {  #with conditional repump, resonant, MBI
                'index' : 9,
                'file' : 'MBI_Multiple_RO_lt2.TB9',
                'params_long' : [           # keep order!!!!!!!!!!!!!
                    ['counter_channel'             ,   1],
                    ['green_laser_DAC_channel'     ,   7],
                    ['Ex_laser_DAC_channel'        ,   6],
                    ['A_laser_DAC_channel'         ,   8],
                    ['AWG_start_DO_channel'        ,   1],
                    ['AWG_done_DI_channel'         ,   8],
                    ['send_AWG_start'              ,   0],
                    ['wait_for_AWG_done'           ,   0],
                    ['green_repump_duration'       ,   5],
                    ['CR_duration'                 ,  50],
                    ['SP_E_duration'                 , 100],
                    ['SP_filter_duration'          ,   0],
                    ['sequence_wait_time'          ,   0],
                    ['wait_after_pulse_duration'   ,   1],
                    ['CR_preselect'                ,  10],
                    ['RO_repetitions'              ,1000],
                    ['RO_duration'                 ,  50],
                    ['sweep_length'                ,  10],
                    ['cycle_duration'              , 300],
                    ['CR_probe'                    ,  10],
                    ['AWG_event_jump_DO_channel'   ,   6],
                    ['MBI_duration'                ,   1],
                    ['wait_for_MBI_pulse'          ,   4],
                    ['SP_A_duration'               , 300],
                    ['MBI_threshold'               , 0  ],
                    ['nr_of_RO_steps'              ,1],
                    ['do_incr_RO_steps'            ,0 ],
                    ['incr_RO_steps'               ,1],
                    ['wait_after_RO_pulse_duration',3 ],
                    ['final_RO_duration'           ,50]
                    ],
                'params_long_index'  : 20,
                'params_long_length' : 25,
                'params_float' : [
                    ['green_repump_voltage' , 0.8],
                    ['green_off_voltage'    , 0.0],
                    ['Ex_CR_voltage'        , 0.8],
                    ['A_CR_voltage'         , 0.8],
                    ['Ex_SP_voltage'        , 0.8],
                    ['A_SP_voltage'         , 0.8],
                    ['Ex_RO_voltage'        , 0.8],
                    ['A_RO_voltage'         , 0.8],
                    ['Ex_final_RO_voltage'  , 0.8],
                    ['A_final_RO_voltage'   , 0]
                    ],
                'params_float_index'  : 21,
                'params_float_length' : 10,
                'par' : {
                    'set_phase_locking_on'      : 19,
                    'set_gate_good_phase'       : 18,}
                },
       
        'MBI_feedback' : {  #with conditional repump, resonant, MBI,and addaptive feedback
                'index' : 9,
                'file' : 'MBI_Feedback_lt2.TB9',
                'params_long' : [           # keep order!!!!!!!!!!!!!
                    ['counter_channel'             ,   1],
                    ['green_laser_DAC_channel'     ,   7],
                    ['Ex_laser_DAC_channel'        ,   6],
                    ['A_laser_DAC_channel'         ,   8],
                    ['AWG_start_DO_channel'        ,   1],
                    ['AWG_done_DI_channel'         ,   8],
                    ['send_AWG_start'              ,   0],
                    ['wait_for_AWG_done'           ,   0],
                    ['green_repump_duration'       ,   5],
                    ['CR_duration'                 ,  50],
                    ['SP_E_duration'                 , 100],
                    ['SP_filter_duration'          ,   0],
                    ['sequence_wait_time'          ,   0],
                    ['wait_after_pulse_duration'   ,   1],
                    ['CR_preselect'                ,  10],
                    ['RO_repetitions'              ,1000],
                    ['RO_duration'                 ,  50],
                    ['sweep_length'                ,  10],
                    ['cycle_duration'              , 300],
                    ['CR_probe'                    ,  10],
                    ['AWG_event_jump_DO_channel'   ,   6],
                    ['MBI_duration'                ,   1],
                    ['wait_for_MBI_pulse'          ,   4],
                    ['SP_A_duration'               , 300],
                    ['MBI_threshold'               , 0  ],
                    ['wait_after_RO_pulse_duration',3   ],
                    ['final_RO_duration'           , 48 ],
                    ['wait_before_final_SP'        , 1],
                    ],
                'params_long_index'  : 20,
                'params_long_length' : 30,
                'params_float' : [
                    ['green_repump_voltage' , 0.8],
                    ['green_off_voltage'    , 0.0],
                    ['Ex_CR_voltage'        , 0.8],
                    ['A_CR_voltage'         , 0.8],
                    ['Ex_SP_voltage'        , 0.8],
                    ['A_SP_voltage'         , 0.8],
                    ['Ex_RO_voltage'        , 0.8],
                    ['A_RO_voltage'         , 0.8],
                    ['Ex_final_RO_voltage'  , 0.8],
                    ['A_final_RO_voltage'   , 0.8],
                    ],
                'params_float_index'  : 21,
                'params_float_length' : 15,
                'par' : {
                    'set_phase_locking_on'      : 19,
                    'set_gate_good_phase'       : 18,},
                
                'data_long' : {
                    'CR_before'                 : 22,
                    'SP'                        : 24,
                    'CR_after_SSRO'             : 23,
                    'PLU_state'                 : 24,
                    'statistics'                : 26,
                    'SN'                        : 30,
                    'FS'                        : 31,
                    'FF'                        : 32,
                    'FinalRO_SN'                : 35,
                    'FinalRO_FS'                : 36,
                    'FinalRO_FF'                : 37,
                    },
                },        
        #MBI + segmented RO (Can in the future be included with other adwin program - Machiel)
        
        'MBI_segmented_ssro' : {
                'index' : 9,
                'file' : 'ssro_MBI_segmented_RO_lt2.TB9',
                'params_long' : [           # keep order!!!!!!!!!!!!!
                    ['counter_channel'             ,   1],
                    ['laser_DAC_channel'    ,   7],
                    ['Ex_laser_DAC_channel'        ,   6],
                    ['A_laser_DAC_channel'         ,   8],
                    ['AWG_start_DO_channel'        ,  16],
                    ['AWG_done_DI_channel'         ,   8],
                    ['send_AWG_start'              ,   0],
                    ['wait_for_AWG_done'           ,   0],
                    ['repump_duration'             ,   5],
                    ['CR_duration'                 ,  50],
                    ['SP_duration'                 , 100],
                    ['SP_filter_duration'          ,   0],
                    ['sequence_wait_time'          ,   0],
                    ['wait_after_pulse_duration'   ,   1],
                    ['CR_preselect'                ,  10],
                    ['SSRO_repetitions'            ,1000],
                    ['SSRO_duration'               ,  50],
                    ['SSRO_stop_after_first_photon',   0],
                    ['cycle_duration'              , 300],
                    ['CR_probe'                    ,  10],
                    ['repump_after_repetitions'    ,  1],
                    ['CR_repump'                   ,  0],
                    ['AWG_event_jump_DO_channel'    ,6],
                    ['segmented_RO_duration'        , 20],
                    ['MBI_duration'                 ,9],
                    ['wait_for_MBI_pulse'           ,3],
                    ['MBI_threshold'                ,1 ],
                    ['sweep_length'                 ,1],
                    ],
                'params_long_index'  : 20,
                'params_long_length' : 30,
                'params_float' : [
                    ['repump_voltage' , 0.8],
                    ['repump_off_voltage'   , 0.07],
                    ['Ex_CR_voltage'        , 0.8],
                    ['A_CR_voltage'         , 0.8],
                    ['Ex_SP_voltage'        , 0.8],
                    ['A_SP_voltage'         , 0.8],
                    ['Ex_RO_voltage'        , 0.8],
                    ['A_RO_voltage'         , 0.8],
                    ['Ex_off_voltage'       , 0.0],
                    ['A_off_voltage'        , -0.08],
                    ['segmented_Ex_RO_voltage',0.1]
                    ],
                'params_float_index'  : 21,
                'params_float_length' : 10,
                'par' : {
                    'completed_reps' : 73,
                    'total_CR_counts' : 70,
                    'CR_threshold' : 25,
                    'last_CR_counts' : 26,
                    },
				'data_long' : {
                    'CR_before' : 22,
                    'CR_after' : 23,
                    'SP_hist' : 24,
                    #'RO_data' : 25,
                    'statistics' : 26,
                    'segment_number' : 27,
                    'full_RO_data' : 28,
                    'segmented_RO_data' : 29,
                    }, 
                },

        'teleportation' : {
                'index' : 9,
                'file' : 'lt2_teleportation.TB9',
                'params_long' : [           # keep order!!!!!!!!!!!!!
                    ['counter_channel'             ,   1],
                    ['repump_laser_DAC_channel'    ,   7],
                    ['Ey_laser_DAC_channel'        ,   6],
                    ['A_laser_DAC_channel'         ,   8],
                    ['repump_duration'             ,  50],
                    ['CR_duration'                 ,  50],
                    ['CR_preselect'                ,  40],
                    ['teleportation_repetitions'   ,1000],
                    ['SSRO_lt2_duration'           ,  50],
                    ['CR_probe'                    ,  40],
                    ['repump_after_repetitions'    ,   1],
                    ['CR_repump'                   ,1000],
                    ['Adwin_lt1_do_channel'        ,   8],
                    ['Adwin_lt1_di_channel'        ,  17],
                    ['AWG_lt2_di_channel'          ,  16]
                    ],
                'params_long_index' : 20, 
                'params_long_length': 25,
                'params_float' : [
                    ['repump_voltage'              , 0.0],
                    ['repump_off_voltage'          , 0.0],
                    ['Ey_CR_voltage'               , 0.0],
                    ['A_CR_voltage'                , 0.0],
                    ['Ey_SP_voltage'               , 0.0],
                    ['A_SP_voltage'                , 0.0],
                    ['Ey_RO_voltage'               , 0.0],
                    ['A_RO_voltage'                , 0.0],
                    ['Ey_off_voltage'              , 0.0],
                    ['A_off_voltage'               , 0.0]
                    ],
                'params_float_index' : 21,
                'params_float_length': 10,
                'par': {
                    'completed_reps' : 77,
                    'total_CR_counts': 70,
                    },
                'data_long' : {
                    'CR_before' : 22, 
                    'CR_after'  : 23,
                    'CR_hist'   : 24,
                    'SSRO_lt2_data' : 25,
                    'statistics'    : 26,
                    },
                },

        #gate modulation
        'check_trigger_from_lt1' : {
                'index' : 9,
                'file' : 'check_trigger_from_lt1.TB9',
                'par' : {},
                'fpar': {}
                },
        
        }

config['adwin_lt1_dacs'] = {
        'atto_x' : 1,
        'atto_y' : 2,
        'atto_z' : 8,
        'green_aom': 4,
        'gate' : 5, #not yet connected
        'velocity1_aom' : 6,
        'velocity2_aom' : 7,
        'yellow_aom' : 3, 
        }

config['adwin_lt1_dios'] = {
        'awg_event' : 6,
        'awg_trigger' : 0,
        'awg_ch3m2' : 9,
        }

config['adwin_lt1_processes'] = {
        
        'init_data' :  {
            'index' : 5, 
            'file' : 'init_data.TB5',
            },


        'linescan' : {
            
            'index' : 2, 
            'file' : 'lt1_linescan.TB2',
            'par' : {
                'set_cnt_dacs' : 1,
                'set_steps' : 2,
                'set_px_action' : 3,
                'get_px_clock' : 4, 
                },
            'fpar' : {
                'set_px_time' : 1,
                'supplemental_data_input' : 2,
                'simple_counting' : 3,  # 1 for simple, 0 for resonant counting
                },
            'data_long' : {
                'set_dac_numbers' : 200,
                'get_counts' : [11,12,13],
                },
            'data_float' : {
                'set_start_voltages' : 199,
                'set_stop_voltages' : 198,
                'get_supplemental_data' : 15,
                },
            },
        
        'counter' : {

            'doc' : '',
            'info' : {
                'counters' : 4,
                },
            'index' : 1, 
            'file' : 'lt1_simple_counting.TB1',
            'par' : {
                'set_integration_time' : 23,
                'set_avg_periods' : 24,
                'set_single_run' : 25,
                'get_countrates' : [41, 42, 43, 44],
                },
            'data_long' : {
                'get_last_counts' : 45,
                },
            },

        'resonant_counting' : {

             'doc' : '',
             'index' : 1,
             'file' : 'lt1_resonant_counting.TB1',
             'par' : {
                 'set_aom_dac' : 63,
                 'set_aom_duration' : 73,
                 'set_probe_duration' : 74,
                 },
             'fpar' : {
                 'set_aom_voltage' : 64,
                 'floating_average': 11, #floating average time (ms)
                 },
             'data_float' : {
                 'get_counts' : [41,42,43,44],
                 },
             },

        'alternating_resonant_counting' : {
            'doc' : '',
            'index' : 1,
            'file' : 'lt1_alternating_resonant_counting.tb1',
            'par' : {
                'set_repump_aom_dac' : 30,
                'set_pump_aom_dac' : 31,
                'set_probe_aom_dac' : 32,
                'set_repump_duration' : 33,
                'set_pump_duration' : 34,
                'set_probe_duration' : 35,
                'set_pp_cycles' : 36,
                'set_floating_average' : 11,
                'set_single_shot' : 37,
                'set_prepump' : 38,
                'set_prepump_duration' : 39,
                },
            'fpar' : {
                'set_repump_aom_voltage' : 30,
                'set_pump_aom_voltage' : 31,
                'set_probe_aom_voltage' : 32,
                },
            },
        
        'set_dac' :  {
            'index' : 3, 
            'file' : 'lt1_set_dac.TB3',
            'par' : {
                'dac_no' : 20,
                },
            'fpar' : {
                'dac_voltage' : 20,
                },
            },
        
        'set_dio' :  {
            'index' : 4, 
            'file' : 'lt1_set_ttl_outputs.TB4',
            'par' : {
                'dio_no' : 61,
                'dio_val' : 62,
                },
            },

        'gate_modulation' : {
            'index' : 7,
            'file' : 'gate_modulation.TB7',
            'par' : {
                'gate_dac' : 12,
                'modulation_period' : 13,
                'modulation_on' : 14,
                },
            'fpar': {
                'gate_voltage' : 12,
                },
            },
        
        # ADwin single-shot readout
        'singleshot' : {
                'index' : 9,
                'file' : 'singleshot_lt1.tb9',
                'par' : {
                    'completed_reps' : 73,
                    'total_CR_counts' : 70,
                    'CR_threshold' : 25,
                    'last_CR_counts' : 26,
                    },
                'fpar' : {
                    },
                'params_long' : [
                    ['counter_channel'             ,   1],
                    ['repump_laser_DAC_channel'    ,   4],
                    ['Ex_laser_DAC_channel'        ,   6],
                    ['A_laser_DAC_channel'         ,   7],
                    ['AWG_start_DO_channel'        ,  16],
                    ['AWG_done_DI_channel'         ,   8],
                    ['send_AWG_start'              ,   0],
                    ['wait_for_AWG_done'           ,   0],
                    ['repump_duration'             ,   5],
                    ['CR_duration'                 ,  50],
                    ['SP_duration'                 , 100],
                    ['SP_filter_duration'          ,   0],
                    ['sequence_wait_time'          ,   0],
                    ['wait_after_pulse_duration'   ,   1],
                    ['CR_preselect'                ,  10],
                    ['SSRO_repetitions'            ,1000],
                    ['SSRO_duration'               ,  50],
                    ['SSRO_stop_after_first_photon',   0],
                    ['cycle_duration'              , 300],
                    ['CR_probe'                    ,  10],
                    ['repump_after_repetitions'    ,  1],
                    ['CR_repump'                   ,  0],
                    ],
                'params_long_index'  : 20,
                'params_long_length' : 25,
                'params_float' : [
                    ['repump_voltage'       , 0.8],
                    ['repump_off_voltage'   , 0.0],
                    ['Ex_CR_voltage'        , 0.8],
                    ['A_CR_voltage'         , 0.8],
                    ['Ex_SP_voltage'        , 0.8],
                    ['A_SP_voltage'         , 0.8],
                    ['Ex_RO_voltage'        , 0.8],
                    ['A_RO_voltage'         , 0.8],
                    ['Ex_off_voltage'       , 0.0],
                    ['A_off_voltage'        , 0.0],
                    ],
                'params_float_index'  : 21,
                'params_float_length' : 10,
                'data_long' : {
                    'CR_before' : 22,
                    'CR_after' : 23,
                    'SP_hist' : 24,
                    'RO_data' : 25,
                    'statistics' : 26,
                    },                    
                },

        # continuous resonant counting (== only the CR of SSRO)
        'continuous_CR' : {
                'index' : 9,
                'file' : 'lt1_continuous_CR.TB9',
                'par' : {
                    'total_CR_counts' : 70,
                    'total_repump_counts' : 76,
                    'CR_preselect' : 75,
                    'CR_probe' : 68,
                    'CR_repump' : 69,
                    'CR_checks' : 71,
                    'CR_below_threshold_events' : 72, 
                    },
                'fpar' : {
                    },
                'params_long' : [
                    ['counter_channel'             ,   1],
                    ['repump_laser_DAC_channel'    ,   4],
                    ['Ex_laser_DAC_channel'        ,   6],
                    ['A_laser_DAC_channel'         ,   7],
                    ['repump_duration'             ,   5],
                    ['CR_duration'                 ,  50],
                    ['CR_preselect'                ,  10],
                    ['cycle_duration'              , 300],
                    ['CR_probe'                    ,  10],
                    ['repump_after_repetitions'    ,  1],
                    ['CR_repump'                   ,  0],
                    ],
                'params_long_index'  : 20,
                'params_long_length' : 25,
                'params_float' : [
                    ['repump_voltage'       , 0.8],
                    ['repump_off_voltage'   , 0.0],
                    ['Ex_CR_voltage'        , 0.8],
                    ['A_CR_voltage'         , 0.8],
                    ['Ex_SP_voltage'        , 0.8],
                    ['A_SP_voltage'         , 0.8],
                    ['Ex_RO_voltage'        , 0.8],
                    ['A_RO_voltage'         , 0.8],
                    ['Ex_off_voltage'       , 0.0],
                    ['A_off_voltage'        , 0.0],
                    ],
                'params_float_index'  : 21,
                'params_float_length' : 10,                
                },

        'singleshot_altern_CR' : {
                'index' : 9,
                'file' : 'singleshot_lt1_altern_cr.tb9', 
                'par' : {
                    'completed_reps' : 73,
                    'total_CR_counts' : 70,
                    'CR_threshold' : 25,
                    'last_CR_counts' : 26,
                    },
                'fpar' : {
                    'gate_voltage' : 26,
                    },
                'params_long' : [
                    ['counter_channel'             ,   1],
                    ['repump_laser_DAC_channel'     ,  4],
                    ['Ex_laser_DAC_channel'        ,   6],
                    ['A_laser_DAC_channel'         ,   7],
                    ['AWG_start_DO_channel'        ,  16],
                    ['AWG_done_DI_channel'         ,   8],
                    ['send_AWG_start'              ,   0],
                    ['wait_for_AWG_done'           ,   0],
                    ['repump_duration'             ,   5],
                    ['CR_pump_duration'            ,  50],
                    ['SP_duration'                 , 100],
                    ['SP_filter_duration'          ,   0],
                    ['sequence_wait_time'          ,   0],
                    ['wait_after_pulse_duration'   ,   1],
                    ['CR_preselect'                ,  10],
                    ['SSRO_repetitions'            ,1000],
                    ['SSRO_duration'               ,  50],
                    ['SSRO_stop_after_first_photon',   0],
                    ['cycle_duration'              , 300],
                    ['CR_probe'                    ,  10],
                    ['CR_probe_duration'           ,  50],
                    ['CR_pp_cycles'                ,   5],
                    ['CR_prepump_duration'         , 100],
                    ],
                'params_long_index'  : 20,
                'params_long_length' : 25,
                'params_float' : [
                    ['repump_voltage' , 0.8],
                    ['repump_off_voltage'    , 0.0],
                    ['Ex_CR_voltage'        , 0.8],
                    ['A_CR_voltage'         , 0.8],
                    ['Ex_SP_voltage'        , 0.8],
                    ['A_SP_voltage'         , 0.8],
                    ['Ex_RO_voltage'        , 0.8],
                    ['A_RO_voltage'         , 0.8],
                    ['yellow_repump_voltage', 0.8],
                    ],
                'params_float_index'  : 21,
                'params_float_length' : 10,
                'data_long' : {
                    'CR_before' : 22,
                    'CR_after' : 23,
                    'SP_hist' : 24,
                    'RO_data' : 25,
                    'statistics' : 26,
                    },
                },
        
        'integrated_ssro' : {
                'index' : 9,
                'file' : 'integrated_ssro_lt1.TB9',
                'params_long' : [           # keep order!!!!!!!!!!!!!
                    ['counter_channel'             ,   1],
                    ['repump_laser_DAC_channel'     ,  4],
                    ['Ex_laser_DAC_channel'        ,   6],
                    ['A_laser_DAC_channel'         ,   7],
                    ['AWG_start_DO_channel'        ,  16],
                    ['AWG_done_DI_channel'         ,   8],
                    ['send_AWG_start'              ,   0],
                    ['wait_for_AWG_done'           ,   0],
                    ['repump_duration'             ,   5],
                    ['CR_duration'                 ,  50],
                    ['SP_duration'                 , 100],
                    ['sweep_length'                ,   1],
                    ['sequence_wait_time'          ,   0],
                    ['wait_after_pulse_duration'   ,   1],
                    ['CR_preselect'                ,  10],
                    ['SSRO_repetitions'            ,1000],
                    ['SSRO_duration'               ,  50],
                    ['SSRO_stop_after_first_photon',   0],
                    ['cycle_duration'              , 300],
                    ['CR_probe'                    ,  10],
                    ['repump_after_repetitions'    ,   1],
                    ['CR_repump'                   ,1000]
                    ],
                'params_long_index'  : 20,
                'params_long_length' : 25,
                'params_float' : [
                    ['repump_voltage'       , 0.8],
                    ['repump_off_voltage'   , 0.0],
                    ['Ex_CR_voltage'        , 0.8],
                    ['A_CR_voltage'         , 0.8],
                    ['Ex_SP_voltage'        , 0.8],
                    ['A_SP_voltage'         , 0.8],
                    ['Ex_RO_voltage'        , 0.8],
                    ['A_RO_voltage'         , 0.8],
                    ['Ex_off_voltage'       , 0.0],
                    ['A_off_voltage'        , 0.0]
                    ],
                'params_float_index'  : 21,
                'params_float_length' : 10,
                'par' : {
                    'completed_reps' : 73,
                    'total_CR_counts' : 70,
                    'CR_events_below_threshold' : 71,
                    'CR_events' : 72,                    
                    # 'CR_threshold' : 75,
                    # 'last_CR_counts' : 26,
                    },
				'data_long' : {
                    'CR_before' : 22,  # not used in the integrated ssro
                    'CR_after' : 23,
                    'SP_hist' : 24,
                    'RO_data' : 25,
                    'statistics' : 26,
                    }, 
                },

        'MBI' : {
                'info' : """
                    Conditional repumping, and resonant readout at the end.
                    Has one MBI step and can read out multiple times (e.g., on different lines).
                    """,
                'index' : 9,
                'file' : 'lt1_MBI.TB9',
                'params_long' : [           # keep order!!!!!!!!!!!!!
                    ['counter_channel'             ,   1],
                    ['repump_laser_DAC_channel'    ,   4],
                    ['Ex_laser_DAC_channel'        ,   6],
                    ['A_laser_DAC_channel'         ,   7],
                    ['AWG_start_DO_channel'        ,   0],
                    ['AWG_done_DI_channel'         ,   9],
                    ['repump_duration'             ,   5],
                    ['CR_duration'                 ,  50],
                    ['SP_E_duration'               , 100],
                    ['wait_after_pulse_duration'   ,   1],
                    ['CR_preselect'                ,  10],
                    ['repetitions'                 ,1000],
                    ['sweep_length'                ,  10],
                    ['cycle_duration'              , 300],
                    ['CR_probe'                    ,  10],
                    ['AWG_event_jump_DO_channel'   ,   6],
                    ['MBI_duration'                ,   1],
                    ['MBI_steps'                   ,   1],
                    ['MBI_threshold'               ,   0],
                    ['nr_of_ROsequences'           ,   1],
                    ['wait_after_RO_pulse_duration',   3],
                    ['CR_repump'                   ,   0],
                    ['repump_after_repetitions'    ,   1],                  
                    ],
                'params_long_index'  : 20,
                'params_long_length' : 30,
                'params_float' : [
                    ['repump_voltage' , 0.8],
                    ['repump_off_voltage'    , 0.0],
                    ['Ex_CR_voltage'        , 0.8],
                    ['A_CR_voltage'         , 0.8],
                    ['Ex_SP_voltage'        , 0.8],
                    ['Ex_MBI_voltage'       , 0.8],
                    ['Ex_off_voltage'       , 0.0],
                    ['A_off_voltage'        , 0.0]
                    ],
                'params_float_index'  : 21,
                'params_float_length' : 6,
                'par' : {
                    'CR_preselect' : 75,
                    'CR_probe' : 68,
                    'completed_reps' : 73,

                    },
                'data_long' : {
                    'CR_before' : 22,
                    'CR_after' : 23,
                    'MBI_attempts' : 24,
                    'MBI_cycles' : 25,
                    'statistics' : 26,
                    'ssro_results' : 27,
                    },
                },
        
        'set_gate_voltage': {

                'index' : 8,
                'file' : 'lt1_set_gate_voltage.TB8',
                'par' : {
                    'gate_dac' : 50,
                },
                'fpar' : {
                    'current_voltage' : 50,
                    'target_voltage' : 51,
                },
        },

        'teleportation' : {

                'info' : """
                    Teleportation master control. LT1 is local, LT2 is remote.
                    """,
                'index' : 9,
                'file' : 'lt1_teleportation_control.TB9',
                'params_long' : [           #Keep order!!!
                    ['counter_channel'              ,       1],
                    ['repump_laser_DAC_channel'     ,       3],
                    ['Ey_laser_DAC_channel'         ,       6],
                    ['FT_laser_DAC_channel'         ,       7],
                    ['CR_duration'                  ,      50],
                    ['CR_threshold_preselect'       ,      30],
                    ['CR_threshold_probe'           ,      10],
                    ['repump_duration'              ,     100],
                    ['time_before_forced_CR'        , 1000000],
                    ['teleportation_repetitions'    ,    1000],
                    ['SSRO1_duration'               ,      50],
                    ['ADwin_lt2_trigger_do_channel' ,       2],
                    ['ADWin_lt2_di_channel'         ,       1],
                    ['AWG_lt1_trigger_do_channel'   ,       1],
                    ['AWG_lt1_di_channel'           ,       3],
                    ['PLU_arm_do_channel'           ,      10],
                    ['PLU_di_channel'               ,       2],
                    ['wait_before_SSRO1'            ,       3],
                    ['wait_before_SP_after_RO'      ,       3],
                    ['SP_after_RO_duration'         ,      50],
                    ['wait_before_SSRO2'            ,       3],
                    ['SSRO2_duration'               ,      50],
                    ['repump_after_repetitions'     ,       1],
                    ['CR_repump'                    ,    1000],
                    ['AWG_lt1_event_do_channel'     ,       3],
                    ['max_CR_starts'                ,       0], 
                    ['AWG_lt2_address0_do_channel'  ,       0],
                    ['AWG_lt2_address1_do_channel'  ,       1],
                    ['AWG_lt2_address2_do_channel'  ,       2],
                    ['AWG_lt2_address3_do_channel'  ,       3],
                    ['AWG_lt2_address_LDE'          ,       1],
                    ['AWG_lt2_address_U1'           ,       2],                    
                    ['AWG_lt2_address_U2'           ,       3],
                    ['AWG_lt2_address_U3'           ,       4],
                    ['AWG_lt2_address_U4'           ,       5],
                    ['do_remote'                    ,       1],
                    ['do_N_polarization'            ,       1],
                    ['do_sequences'                 ,       1],
                    ],
                'params_long_index'    : 20,
                'params_long_length'   : 40,
                'params_float' : [          
                    ['repump_voltage'              ,     0.0],
                    ['repump_off_voltage'            ,     0],
                    ['Ey_CR_voltage'                ,   0.0],
                    ['FT_CR_voltage'                 ,   0.0],
                    ['Ey_SP_voltage'                ,   0.0],
                    ['FT_SP_voltage'                 ,   0.0],
                    ['Ey_RO_voltage'                ,   0.0],
                    ['FT_RO_voltage'                 ,   0.0],       
                    ['Ey_off_voltage'                ,   0.0],
                    ['FT_off_voltage'                 ,   0.0],                        
                    ],
                'params_float_index'    : 21,
                'params_float_length'   : 10,
                'par' : {
                    'CR_preselect'  : 75,
                    'CR_probe'      : 68,
                    'completed_reps' : 77,
                    'total_red_CR_counts' : 70,
                    },
                'data_long' : {
                    'CR_hist_time_out' : 7,
                    'CR_hist_all' : 8,
                    'CR_hist_yellow_time_out' : 9,
                    'CR_hist_yellow_all' : 10,
                    'CR_after' : 23,
                    'statistics' : 28,
                    'SSRO1_results' : 24,
                    'SSRO2_results' : 26,
                    'PLU_Bell_states' : 25,
                    'CR_before' : 27,
                    },
                },        
        }
